Repository metal3-io/metal3-dev-env, pull requests merged in 2019-12, with the labels that each got.

#143 Run Baremetal operator in a loop locally
  03_launch_mgmt_cluster.sh
  hack/run-bmo-loop.sh
Labels: approved, lgtm, size/M

#142 Move hard-coded networks into vars file
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/common/tasks/main.yml
Labels: approved, lgtm, size/M

#141 firewalld: don't restart, only ensure it's started
  vm-setup/roles/firewall/tasks/firewalld.yaml
Labels: approved, lgtm, size/S

#146 Add missing ovs role
  vm-setup/roles/libvirt/tasks/network_setup_tasks.yml
  vm-setup/roles/ovs/defaults/main.yml
  vm-setup/roles/ovs/tasks/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#147 Add the ability to define a portgroup for a network
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, ok-to-test, size/S

#96 Enable IPv6 Support for Provisioning
  .gitignore
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  clouds.yaml
  config_example.sh
  lib/common.sh
  scripts/v1alpha1/create_machine.sh
  scripts/v1alpha1/user_data.sh
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: approved, lgtm, size/L

#150 Update check_bmh_status to take multiple provisioning states as input
  05_test.sh
Labels: approved, lgtm, ok-to-test, size/XS

#151 Cast virtualbmc_base_port to int
  vm-setup/roles/common/tasks/vm_nodes_tasks.yml
Labels: approved, lgtm, size/XS

#152 Use v1alpha1 branch and master for v1alpha2
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#153 Change V1ALPHA2_SWITCH variable to CAPI_VERSION
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README_v1alpha2.md
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, size/M

#154 Update k8s version - 1.17
  lib/common.sh
Labels: approved, lgtm, size/XS

#155 Wrap vbmc_address in square brackets if IPv6
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, size/XS

#148 Merge packages installation in v1alpha2 crs
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/workers_centos.yaml
  crs/v1alpha2/workers_ubuntu.yaml
Labels: approved, lgtm, size/M
