Repository metal3-io/metal3-dev-env, pull requests merged in 2019-10, with the labels that each got.

#67 List command the script is blocking on.
  lib/common.sh
Labels: size/XS

#70 Makefile: Add a lint target.
  02_configure_host.sh
  Makefile
Labels: size/XS

#73 Clean-up minikube VM correctly
  Makefile
Labels: size/XS

#75 Add script that runs shellcheck how it will run in CI.
  01_prepare_host.sh
  Makefile
  hack/shellcheck.sh
  lib/common.sh
  lib/logging.sh
  vm-setup/roles/libvirt/files/get-domain-ip.sh
Labels: size/M

#76 Create OWNERS file.
  OWNERS
Labels: size/XS

#71 Add interface check for Minikube
  01_prepare_host.sh
Labels: size/S

#77 Fix iteration in verify script
  04_verify.sh
Labels: approved, lgtm, size/S

#61 Add a switch to use redfish as BMC driver
  config_example.sh
  lib/common.sh
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm

#68 Move ironic into cluster
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  04_verify.sh
  host_cleanup.sh
  lib/common.sh
Labels: approved, lgtm, size/L

#81 Increase timeout limit for tests
  lib/common.sh
Labels: approved, lgtm, needs-ok-to-test, size/XS

#80 Small updates for lint-tests to succeed
  README.md
  lib/logging.sh
Labels: approved, lgtm, ok-to-test, size/XS

#83 Add hack/markdownlint.sh.
  hack/markdownlint.sh
Labels: approved, lgtm, size/S

#82 Provide clouds.yaml for interacting with Ironic
  02_configure_host.sh
  clouds.yaml
  lib/common.sh
Labels: approved, lgtm, size/S

#78 Add v1alpha2 CAPI and CABPK controllers and CRDs
  03_launch_mgmt_cluster.sh
  04_verify.sh
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, ok-to-test, size/L

#89 Fix iptables rules for PXE boot
  02_configure_host.sh
Labels: approved, lgtm, size/S

#92 refactor minikube initialization
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: approved, lgtm, size/M

#95 Clean-up interfaces on RHEL as well
  host_cleanup.sh
Labels: approved, lgtm, size/XS

#97 Add iptables rule to allow mdns for ironic on provisioning
  02_configure_host.sh
Labels: approved, lgtm, size/S

#90 Pre-pull images in Minikube
  01_prepare_host.sh
  02_configure_host.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#101 Upgrade to python3 in dev-env for ubuntu
  ubuntu_install_requirements.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: approved, lgtm, size/S

#91 Use ansible to setup firewalld or iptables rules as appropriate
  02_configure_host.sh
  lib/common.sh
  vm-setup/firewall.yml
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/firewall/tasks/iptables.yaml
  vm-setup/roles/firewall/tasks/main.yml
Labels: approved, lgtm, size/L

#105 Fix bug in test script
  05_test.sh
Labels: approved, lgtm, size/XS

#106 Fix iptables missing established and related rule on provisioning
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: approved, lgtm, size/XS

#94 Adding v1alpha2 CRs, runs controller locally
  03_launch_mgmt_cluster.sh
  05_test.sh
  crs/v1alpha2/cluster.yaml
  crs/v1alpha2/controlplane.yaml
  crs/v1alpha2/machinedeployment.yaml
  lib/common.sh
  scripts/v1alpha1/create_machine.sh
  scripts/v1alpha2/create_cluster.sh
  scripts/v1alpha2/create_v1alpha2_machine.sh
Labels: approved, lgtm, ok-to-test, size/L

#104 Support for local image building
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: approved, lgtm, size/M

#108 Fix Kustomize installation
  01_prepare_host.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#110 Add image pulling and container verifications for registry
  01_prepare_host.sh
  04_verify.sh
Labels: approved, lgtm, size/XS

#114 Temporary workaround for kubernetes/minikube#5751
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#115 Revert temporary workaround for kubernetes/minikube #5751
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#113 Install golang using playbook
  01_prepare_host.sh
  lib/common.sh
  vm-setup/install-package-playbook.yml
  vm-setup/requirements.yml
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: approved, lgtm, size/S

#117 Increase minikube memory to 4096MB
  01_prepare_host.sh
Labels: approved, lgtm, size/XS

#112 Parameterize host image and use Cirros or Ubuntu
  01_prepare_host.sh
  02_configure_host.sh
  05_test.sh
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, size/M

#120 Drop support for RHEL7
  lib/common.sh
Labels: approved, lgtm, size/M

#119 modify 05_test.sh to use primary interface for ssh
  05_test.sh
  ip_range_check.py
  lib/common.sh
Labels: approved, lgtm, size/M
