Repository metal3-io/metal3-dev-env, pull requests merged in 2019-11, with the labels that each got.

#122 Install go 1.12.12 instead of 1.12.0
  vm-setup/install-package-playbook.yml
  vm-setup/requirements.yml
Labels: approved, lgtm, size/XS

#123 Correctly use fork of fubarhouse.golang
  vm-setup/requirements.yml
Labels: approved, lgtm, size/XS

#109 Move user_data.sh to scripts/v1alpha1
  scripts/v1alpha1/create_machine.sh
  scripts/v1alpha1/user_data.sh
Labels: approved, lgtm, size/XS

#126 provision_host.sh: Fix path to user_data.sh
  provision_host.sh
Labels: approved, lgtm, size/XS

#125 Modify the v1alpha2 deployment script
  02_configure_host.sh
  README_v1alpha2.md
  crs/v1alpha2/controlplane.yaml
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/machinedeployment.yaml
  crs/v1alpha2/workers_centos.yaml
  crs/v1alpha2/workers_ubuntu.yaml
  lib/common.sh
  scripts/v1alpha2/create_controlplane.sh
  scripts/v1alpha2/create_v1alpha2_machine.sh
  scripts/v1alpha2/create_worker.sh
  scripts/v1alpha2/delete_controlplane.sh
  scripts/v1alpha2/delete_v1alpha2_machine.sh
  scripts/v1alpha2/delete_worker.sh
Labels: approved, lgtm, size/XL

#127 Fix curl command in v1alpha2 instructions
  README_v1alpha2.md
Labels: approved, lgtm, size/XS

#128 Fix local run config for BMO+Ironic container
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, ok-to-test, size/XS

#132 add metal3.io labels in v1alpha2 crs
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/workers_centos.yaml
  crs/v1alpha2/workers_ubuntu.yaml
Labels: approved, lgtm, size/XS

#134 Use upstream repo for golang setup
  vm-setup/requirements.yml
Labels: approved, lgtm, ok-to-test, size/XS

#131 Add verification for v1alpha2 deployment
  04_verify.sh
Labels: approved, lgtm, size/M

#135 Fix issue with labels in cloud-init
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/workers_centos.yaml
  crs/v1alpha2/workers_ubuntu.yaml
Labels: approved, lgtm, size/XS

#118 create ssh keys in lib/common and set environment variable
  02_configure_host.sh
  05_test.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#129 Generate node data based on flavors map
  02_configure_host.sh
  05_test.sh
  lib/common.sh
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/common/tasks/main.yml
  vm-setup/roles/common/tasks/vm_nodes_tasks.yml
  vm-setup/roles/libvirt/tasks/network_setup_tasks.yml
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, size/M

#137 Verify introspection by checking ready or available status
  04_verify.sh
Labels: approved, lgtm, ok-to-test, size/XS

#139 Modify v1alpha2 CRs to add noCloudProvider option
  crs/v1alpha2/cluster.yaml
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
Labels: approved, lgtm, size/XS
