Repository metal3-io/metal3-dev-env, pull requests merged in 2020-09, with the labels that each got.

#377 Verify retrieval of kubelet and kubeadm configuration files
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/M

#412 Feature test documentation update
  scripts/feature_tests/README.md
Labels: approved, lgtm, size/M

#447 Bump ansible to latest
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#428 CI: upgrade test fixes
  Makefile
  scripts/feature_tests/setup_env.sh
  scripts/feature_tests/upgrade/1cp_1w_bootDiskImage_cluster_upgrade.sh
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  scripts/feature_tests/upgrade/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/L

#450 Add support for tilt based deployments
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  config_example.sh
  lib/releases.sh
  vars.md
Labels: approved, lgtm, size/L

#451 Create clusterctl local folder with overrides
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#445 Update Centos to use Metal3DataTemplate
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
Labels: approved, lgtm, size/S

#452 Fetch pre-Baked Ubuntu node image
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#456 Update images before running ironic_run_local.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#448 CI: improve upgrade test coverage
  scripts/feature_tests/upgrade/clean_setup_env.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
Labels: approved, lgtm, size/L

#459 Fix Calico setup for Centos nodes
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/XS

#460 Update var doc with CAPI_VERSION var
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#458 Integer comparison modified to follow POSIX rules
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/S

#463 Parameterize external_subnet_v4
  vm-setup/roles/firewall/defaults/main.yml
Labels: approved, lgtm, size/XS

#464 Disable Basic authentication and CA certs in BMO for Ironic
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#461 Decouple pivot and re-pivot actions
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
Labels: approved, lgtm, size/M

#467 Add Missing IP in Metal3 Data Template for Centos
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: approved, lgtm, size/S

#465 Add usr/local/go/bin to the PATH env var
  01_prepare_host.sh
Labels: approved, lgtm, size/XS

#469 Introduce 'repivoting' action
  scripts/feature_tests/pivoting/Makefile
  scripts/feature_tests/pivoting/repivot.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#471 Fix ansible version to 2.9.13 to fix CI
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#479 Extend the waiting time for BMH deprovisioning
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
Labels: approved, lgtm, size/XS

#477 Update docker version for centos nodes
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
Labels: approved, lgtm, size/XS

#475 Separate pivoting action for priority upgrade use case.
  scripts/feature_tests/pivoting/Makefile
  scripts/feature_tests/pivoting/upgrade.sh
Labels: approved, lgtm, size/S

#476 Remove route configuration from controlplane and worker templates in Centos
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: approved, lgtm, size/S

#473 Update ubuntu node Image
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#480 Add ironic endpoint bridge in Centos nodes
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
Labels: approved, lgtm, size/M

#481 Add Jaakko-Os smoshiur1237 and fgofurov7 as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#484 Add missing quotes to avoid re-installing Clusterctl
  01_prepare_host.sh
Labels: approved, lgtm, size/XS

#483 Make common functions cluster agnostic
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/M

#482 Modify CAPM3 to import local BMO and IPAM
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: approved, lgtm, size/L

#485 Create missing file when installing clusterctl
  01_prepare_host.sh
Labels: approved, lgtm, size/XS

#486 Add pre-baked Centos Image
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#489 Add action for verify script before pivoting in upgrade task.
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#488 Parameterize registry endpoint
  02_configure_host.sh
  lib/network.sh
  vm-setup/install-package-playbook.yml
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#490 Update cirros version
  config_example.sh
  lib/images.sh
Labels: approved, lgtm, ok-to-test, size/S
