Repository metal3-io/metal3-dev-env, pull requests merged in 2020-03, with the labels that each got.

#240 Remove python interpeter switching tasks in Ansible
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_worker.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_worker.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/S

#241 Wrap IPv6 URL's for BMC's
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm, size/XS

#242 Use RDO packages when installing virtualbmc
  resources/vbmc/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#239 Rename CAPBM to CAPM3
  03_launch_mgmt_cluster.sh
  04_verify.sh
  config_example.sh
  hack/run-bmo-loop.sh
  host_cleanup.sh
  lib/common.sh
Labels: approved, lgtm, size/L

#237 Upgrade to golang 1.14
  ubuntu_install_requirements.sh
  vm-setup/install-package-playbook.yml
Labels: approved, lgtm, size/XS

#225 Replace ipcalc with python script
  lib/network.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, ok-to-test, size/XS

#244 Remove v1alpha1 CI status badges
  README.md
Labels: approved, lgtm, size/XS

#243 Update dev-env with new CAPM3 repo
  03_launch_mgmt_cluster.sh
  04_verify.sh
  config_example.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/L

#245 Change CAPM3 image used and CAPM3 repo in config_example
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#246 Add CAPM3 v1alpha4
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  README_v1alphaX.md
  hack/markdownlint.sh
  hack/shellcheck.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/XL

#248 Update README based on PR#216
  README_v1alphaX.md
Labels: approved, lgtm, size/XS

#250 Rename test scripts to reflect v1a1 deprecation
  05_test.sh
  05_test_v1aX.sh
  05_test_v1alpha1.sh
  Makefile
Labels: approved, lgtm, size/L

#251 Add DHCPv6 ports to pxe_udp_ports list for firewall
  vm-setup/roles/firewall/defaults/main.yml
Labels: approved, lgtm, size/XS

#252 Add dns port to libvirt's firewall zone
  vm-setup/roles/firewall/defaults/main.yml
Labels: approved, lgtm, size/XS

#254 Fix CAPI version conditional
  lib/common.sh
Labels: approved, lgtm, size/XS

#255 Use Kubeadm Kubelet extraArgs to set providerID in node templates
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/S

#256 Make openstackclient.sh more flexible
  openstackclient.sh
Labels: approved, lgtm, size/S

#247 Update sushy container image
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#259 Add support for repositories cloned beforehand
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/M

#260 Fix unset variable for image name
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#262 Do not checkout BMO and CAPM3 branch if folder already exists
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/M

#257 Set API version explicitly to v1alpha2 when condition is met.
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/S

#261 Remove duplicated Ansible tasks
  vm-setup/roles/v1aX_integration_test/tasks/download_image.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#264 Target cluster OS set to Centos8 instead of CentOS 7
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/tasks/provision_cluster.yml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#266 Add machine status check in test playbook
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/S

#270 Upgrade k8s version to 1.18
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#272 Use dnf instead of yum
  centos_install_requirements.sh
Labels: approved, lgtm, ok-to-test, size/S

#268 Ensure python-pip package exists when libvirtd server is running CentOS 7
  centos_install_requirements.sh
Labels: approved, lgtm, size/XS

#274 Change some URL links from http to https
  README.md
  README_v1alphaX.md
Labels: approved, lgtm, size/XS

#253 Add ability to specity external SRV records
  vm-setup/roles/common/defaults/main.yml
Labels: approved, lgtm, ok-to-test, size/XS

#275 Remove v1a2 CI status badge
  README.md
Labels: approved, lgtm, size/XS

#238 Wire in hostname configuration option
  02_configure_host.sh
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, ok-to-test, size/XS

#269 Remove openstackclient container after use
  openstackclient.sh
Labels: approved, lgtm, size/XS
