Repository metal3-io/metal3-dev-env, pull requests merged in 2020-08, with the labels that each got.

#390 CI: add upgrade combined test
  Makefile
  scripts/feature_tests/README.md
  scripts/feature_tests/setup_env.sh
  scripts/feature_tests/upgrade/README.md
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
Labels: approved, lgtm, size/L

#413 Advance sushy-tools version
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#420 Update ironic images to locally built for v1alpha4 deployments
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#407 Add small note regarding resource requirements for feature tests
  scripts/feature_tests/README.md
Labels: approved, lgtm, size/XS

#417 Add fmuyassarov as approver
  OWNERS
Labels: approved, lgtm, size/XS

#416 Use Ubuntu20 for target nodes
  README.md
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#415 Revert "Add IRONIC_AUTH_STRATEGY"
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#411 Upgrade test script improvement
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/XS

#422 Preload kind container image
  01_prepare_host.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#423 Fix incorrect ci tests and add verification
  05_test.sh
  lib/common.sh
  scripts/fetch_manifests.sh
  scripts/run.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#425 Add keepalived image variable
  lib/common.sh
Labels: approved, lgtm, size/XS

#426 Uplift calico version to latest
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/XS

#408 Fix filtering objects' name in remediation tests
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/M

#421 Install clusterctl binary with curl
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#414 Use local registry for images and pre-populate them.
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/M

#429 Fix CAPM3 Makefile target
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#431 Bug fix: Start local image registry container if it is in exited status.
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#433 Small fix: Deleting unused variables in Metal3-dev-env
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#437 Fix symlink issue in monitor.keepalived.service in cloud-init
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/XS

#435 Adding test for marking unhealthy node in remediation process.
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/L

#441 Bug Fix: Local registry connection error during Metal3 deployment.
  02_configure_host.sh
Labels: approved, lgtm, size/XS
