Repository metal3-io/metal3-dev-env, pull requests merged in 2020-06, with the labels that each got.

#330 Log libvirt serial consoles to a file
  host_cleanup.sh
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: approved, lgtm, size/S

#329 Add Ansible script for remediation test
  scripts/v1alphaX/remediation.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#328 Add pivoting test ansible script
  README.md
  scripts/v1alphaX/pivot.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#333 Remove hardcoded IPs for external subnet
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  centos_install_requirements.sh
  host_cleanup.sh
  lib/common.sh
  lib/network.sh
  ubuntu_bridge_network_configuration.sh
  ubuntu_install_requirements.sh
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: approved, lgtm, ok-to-test, size/M

#294 Export variables to make BMO as part of CAPM3 deployment
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#334 Fix BMO local image bug and update kustomize version
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/templates/kustomization_empty.yaml
Labels: approved, lgtm, size/S

#335 Update registry IP in kind configuration
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#336 🌱 Export missing variables in BMO as part of CAPM3 deployment
  03_launch_mgmt_cluster.sh
  lib/network.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#339 Upgrade test Makefile update
  scripts/feature_tests/upgrade/Makefile
Labels: approved, lgtm, size/XS

#340 Fix CAPI_VERSION variable
  lib/common.sh
Labels: approved, lgtm, size/S

#341 Fix exporting variables for provisioning
  scripts/feature_tests/README.md
  scripts/feature_tests/pivoting/Makefile
  scripts/feature_tests/remediation/Makefile
  scripts/feature_tests/upgrade/Makefile
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/S

#337 Take CAPM3 Metadata and IPAM feature into use for target cluster
  lib/network.sh
  ubuntu_bridge_network_configuration.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XL

#338 ✨ Adapt metal3-dev-env to BMO as part of CAPM3 deployment
  03_launch_mgmt_cluster.sh
  04_verify.sh
  lib/network.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#332 initialize reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#344 Update to sushy-tools 0.10.0
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#345 Add IPAM verifications for v1alpha4
  03_launch_mgmt_cluster.sh
  04_verify.sh
Labels: approved, lgtm, size/M

#346 Add export of CAPM3RELEASE for use in ansible
  lib/common.sh
Labels: approved, lgtm, size/XS

#320 Use raw image streaming when deploying
  01_prepare_host.sh
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#349 Reduce target vm ram to 4096 by default
  README.md
  lib/common.sh
Labels: approved, lgtm, size/S

#347 Update BMO deployment & Add Pivot Back
  scripts/feature_tests/pivoting/Makefile
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_cleanup.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#350 Fix ansible version for centos to 2.9.8
  centos_install_requirements.sh
Labels: approved, lgtm, size/XS

#355 Simplify ansible tasks to deploy / undeploy target cluster
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_worker.yml
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_worker.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template.yaml
  vm-setup/roles/v1aX_integration_test/templates/kustomization.yaml
  vm-setup/roles/v1aX_integration_test/templates/kustomization_empty.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XXL
