Repository metal3-io/metal3-dev-env, pull requests merged in 2020-12, with the labels that each got.

#567 Use remove_local_ironic script from BMO
  03_launch_mgmt_cluster.sh
  cluster_cleanup.sh
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
Labels: approved, lgtm, size/S

#563 Remove Centos7 support
  01_prepare_host.sh
  centos_install_requirements.sh
  lib/common.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: approved, lgtm, size/L

#575 Fix centos minikube networking
  lib/common.sh
Labels: approved, lgtm, size/XS

#571 Enable upgrade test for ubuntu.
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/S

#573 Fix bug regarding Ironic deployment in feature test
  scripts/feature_tests/cleanup_env.sh
Labels: approved, lgtm, size/S

#569 Upgrade K8s version to k8s 1.19.3
  config_example.sh
  lib/common.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#568 Paremeterize dhcp pool for Baremetal network
  lib/network.sh
  vm-setup/roles/common/defaults/main.yml
Labels: approved, lgtm, size/S

#570 Add console=ttyS0 to kernel params
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#576 Upgrade k8s version from 1.19.3 to 1.19.4 in upgrade workflow.
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/S

#457 *: allow for fetching Flatcar images
  01_prepare_host.sh
  README.md
  lib/images.sh
Labels: approved, lgtm, ok-to-test, size/S

#578 Bump sushy-tools to 0.13.0
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#580 Fix ownership/filenames for basic_auth
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#579 Initial support for testing with a live-iso
  01_prepare_host.sh
  lib/images.sh
Labels: approved, lgtm, size/S
