Repository metal3-io/metal3-dev-env, pull requests merged in 2020-01, with the labels that each got.

#166 Fix host_cleanup.sh to set num_nodes
  host_cleanup.sh
Labels: approved, lgtm, ok-to-test, size/XS

#168 Create additional infra pod for podman
  02_configure_host.sh
  host_cleanup.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#170 add infra pod creation for httpd, vbmc and sushy-tools containers
  01_prepare_host.sh
Labels: approved, lgtm, size/S

#169 Fixing typos
  04_verify.sh
Labels: approved, lgtm, ok-to-test, size/XS

#171 Configure insecure registry for docker
  02_configure_host.sh
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/S

#173 Change dockerfile location depending on repo
  02_configure_host.sh
Labels: approved, lgtm, size/S

#174 Restart docker after adding daemon.json
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#175 modify BMO image tags to sync with operator_ironic.yaml
  lib/common.sh
Labels: approved, lgtm, size/XS

#176 Modify httpd container name in 04_verify.sh
  04_verify.sh
Labels: approved, lgtm, size/XS

#177 Create docker etc folder before moving daemon.json
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#178 Iterate kubectl commands in 05_test.sh
  05_test.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: approved, lgtm, size/L

#179 Modify deployment method for CAPBM
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/common.sh
Labels: approved, lgtm, size/L

#163 Fix Networking in Ubuntu ControlPlane CR
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/workers_ubuntu.yaml
Labels: approved, lgtm, size/M

#165 kill run-bmo-loop.sh script during host cleanup
  host_cleanup.sh
Labels: approved, lgtm, ok-to-test, size/XS

#181 Add builds status to Readme
  README.md
Labels: approved, lgtm, size/XS

#182 Add a branch checkout in the image building step
  02_configure_host.sh
Labels: approved, lgtm, size/S

#183 Remove unused variables
  lib/common.sh
Labels: approved, lgtm, size/XS

#140 Add Ansible role for v1alpha2 integration test.
  04_verify.sh
  05_test_v1a2.sh
  Makefile
  centos_install_requirements.sh
  lib/common.sh
  ubuntu_install_requirements.sh
  vm-setup/roles/common/tasks/main.yml
  vm-setup/roles/libvirt/tasks/network_setup_tasks.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
  vm-setup/roles/v1a2_integration_test/tasks/deprovision.yml
  vm-setup/roles/v1a2_integration_test/tasks/main.yml
  vm-setup/roles/v1a2_integration_test/tasks/provision.yml
  vm-setup/roles/v1a2_integration_test/tasks/verify.yml
  vm-setup/roles/v1a2_integration_test/templates/cluster.yaml
  vm-setup/roles/v1a2_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1a2_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1a2_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1a2_integration_test/templates/workers_ubuntu.yaml
  vm-setup/roles/v1a2_integration_test/vars/main.yml
  vm-setup/v1a2_integration_test.yml
Labels: approved, lgtm, size/XL

#186 Update CI crs based on #163 and #185 PRs.
  vm-setup/roles/v1a2_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1a2_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/M

#184 Allow vrrp & icmp on provisioning network
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: approved, lgtm, size/S

#185 Make network configuration uniform for controllers and workers
  crs/v1alpha2/workers_ubuntu.yaml
Labels: approved, lgtm, size/XS

#189 Make provisioning network configurable
  .gitignore
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  04_verify.sh
  05_test.sh
  05_test_v1a2.sh
  clouds.yaml
  clouds.yaml.template
  lib/common.sh
  lib/images.sh
  lib/network.sh
  provision_host.sh
  ubuntu_bridge_network_configuration.sh
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm, size/L

#190 Source missing variables for provisioning
  scripts/v1alpha2/create_controlplane.sh
  scripts/v1alpha2/create_worker.sh
  scripts/v1alpha2/delete_controlplane.sh
  scripts/v1alpha2/delete_worker.sh
Labels: approved, lgtm, size/M

#160 Enable testing with an IPv6 EXTERNAL_SUBNET
  lib/common.sh
  lib/network.sh
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, size/S

#193 Install 5.10.0 version of libvirt-python
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: approved, lgtm, size/XS

#192 Changing the sequence of sourcing variables for CRs
  scripts/v1alpha2/create_controlplane.sh
  scripts/v1alpha2/create_worker.sh
  scripts/v1alpha2/delete_controlplane.sh
  scripts/v1alpha2/delete_worker.sh
Labels: approved, lgtm, size/S

#197 Add v1alpha3 CAPBM version
  03_launch_mgmt_cluster.sh
  Makefile
Labels: approved, lgtm, size/S

#203 Hack to fix oniguruma conflict on CentOS 7
  centos_install_requirements.sh
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#206 Add missing ipcalc dependency to Ubuntu install
  ubuntu_install_requirements.sh
Labels: approved, lgtm, ok-to-test, size/XS
