Repository metal3-io/metal3-dev-env, pull requests merged in 2020-05, with the labels that each got.

#302 :bug: CAPM3 local image registry path faulty
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#300 Add user named metal3 for target machine.
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, ok-to-test, size/M

#303 Remove fixed CAPI version and override images with local
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#305 Fix exporting the image variable after override
  03_launch_mgmt_cluster.sh
Labels: approved, size/XS

#306 Fix the local image variable setting
  03_launch_mgmt_cluster.sh
Labels: approved, size/XS

#308 Fix CAPM3 branch depending on CAPI version
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#309 Temporary workaround for ironic issues
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#312 Add local registry as insecure for podman
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#313 Sync keepalived status with of API server
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/M

#310 Clean up ironic-endpoint-keepalived container during make clean
  cluster_cleanup.sh
  host_cleanup.sh
  vm-setup/roles/libvirt/tasks/network_teardown_tasks.yml
Labels: approved, lgtm, size/XS

#315 vbmc: work around old pyghmi in RDO
  resources/vbmc/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#317 Fix text off logs for sync keepalived
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/S

#318 fix: enable and start monitor.keepalived.service
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/XS

#319 Remove interactive terminal from openstackclient.sh
  openstackclient.sh
Labels: approved, lgtm, size/XS

#311 Add firewall rules state "absent" during make clean in Metal3-dev-env
  host_cleanup.sh
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: approved, lgtm, ok-to-test, size/S

#321 Remove container images pre-pull
  01_prepare_host.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#325 Fix docker version on centos target environment
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
Labels: approved, lgtm, size/XS

#324 Run ironic in minikube for CentOS
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#322 Remove v1alpha1 scripts
  config_example.sh
  deprovision_host.sh
  provision_host.sh
  scripts/v1alpha1/create_machine.sh
  scripts/v1alpha1/user_data.sh
Labels: approved, lgtm, size/L

#326 Parameterize vars & clean up unused ones
  config_example.sh
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_worker.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#327 :Fix: Variablize ironic endpoint bridge name
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#323 Add image checksum type and format for target cluster
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/S
