Repository metal3-io/metal3-dev-env, pull requests merged in 2020-07, with the labels that each got.

#356 Add static IP on Ironic endpoint for CAPM3 v1alpha4 ubuntu templates
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/M

#361 Make CAPI-controllers's version configurable
  03_launch_mgmt_cluster.sh
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#362 Bump python to 3.8 and install sushy-tools from git
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#359 Allow using redfish-virtualmedia as protocol type for BMC's
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm, size/XS

#367 Avoid printing skipped Ansible tasks
  lib/common.sh
Labels: approved, lgtm, size/XS

#370 Removes loop where there is only a single item
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: approved, lgtm, size/XS

#358 Add veth interface to keep provisioning bridge up
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  ubuntu_bridge_network_configuration.sh
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/libvirt/tasks/network_teardown_tasks.yml
Labels: approved, lgtm, size/M

#372 Pin sushy-tools to 0.11.0
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#375 Remove metal3 namespace from Calico manifest
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/XS

#371 Fix image download and add raw image creation
  vm-setup/roles/v1aX_integration_test/tasks/download_image.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#379 Add jan-est as reviewer
  OWNERS
Labels: approved, size/XS

#378 Remove PROVISIONING_INTERFACE customization
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#381 Add tests verifying cluster deletion
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
Labels: approved, lgtm, size/M

#373 Bug fix: Assign 172.22.0.2 address to ironic BMO configmap.
  lib/network.sh
Labels: approved, lgtm, ok-to-test, size/S

#380 Add xenwar as a reviwer
  OWNERS
Labels: approved, lgtm, size/XS

#382 Enable dhcp on ironicendpoint interface for v1alpha3
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#383 Fallback to first network if other not found
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm, size/XS

#384 Workaround for CAPI bug
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
Labels: approved, lgtm, size/XS

#343 Add HA cluster remediation tests
  scripts/feature_tests/remediation/Makefile
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/power_cycle.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/L

#376 Move list of vars from try-it.md to Readme here
  README.md
  hack/markdownlint.sh
  vars.md
Labels: approved, lgtm, size/M

#352 Add new "mixed" vm_driver
  config_example.sh
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/firewall/tasks/iptables.yaml
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: approved, lgtm, size/M

#365 Add user check to avoid running as root
  01_prepare_host.sh
Labels: approved, lgtm, needs-ok-to-test, size/XS

#389 Add IRONIC_AUTH_STRATEGY
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#392 Save cluster manifests for debugging
  vm-setup/roles/v1aX_integration_test/files/fetch_manifests.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#393 Bug fix feature test issue with machine remediation.
  vm-setup/roles/v1aX_integration_test/tasks/power_cycle.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, ok-to-test, size/L

#395 force hosts to use legacy boot mode
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#394 Add support for Ubuntu 20.04
  lib/common.sh
  ubuntu_install_requirements.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: approved, lgtm, size/M

#357 Add Automated tests for upgrade workflow
  scripts/feature_tests/upgrade/1cp_1w_bootDiskImage_cluster_upgrade.sh
  scripts/feature_tests/upgrade/Makefile
  scripts/feature_tests/upgrade/README.md
  scripts/feature_tests/upgrade/controlplane_components_upgrade/upgrade_CAPI_and_CAPM3_with_clusterctl.sh
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
Labels: approved, lgtm, size/XL

#397 Fix local repository checkout
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#391 Allow the ironic image to run the baremetal command
  02_configure_host.sh
  openstackclient.sh
Labels: approved, lgtm, size/S

#398 Default to docker for ubuntu based dev-env
  lib/common.sh
Labels: approved, lgtm, size/S

#399 Add checks when fetching github releases
  lib/common.sh
Labels: approved, lgtm, size/S

#400 Fix inconsistency in version variable names and content
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  config_example.sh
  lib/common.sh
  scripts/feature_tests/README.md
  vars.md
  vm-setup/roles/v1aX_integration_test/files/fetch_manifests.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
  vm-setup/v1aX_integration_test.yml
Labels: approved, lgtm, size/L

#401 Fix typos in feature tests readme
  scripts/feature_tests/README.md
Labels: approved, lgtm, size/XS

#402 Fix bmhosts_crs path issue
  scripts/feature_tests/cleanup_env.sh
Labels: approved, lgtm, size/XS

#385 Improve remediation tasks
  scripts/feature_tests/README.md
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/power_cycle.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/L

#406 Fix k8s node filtering for remediation tests
  vm-setup/roles/v1aX_integration_test/tasks/power_cycle.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/S

#405 Add small update feature test remediation task
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/XS
