Repository metal3-io/metal3-dev-env, pull requests merged in 2020-10, with the labels that each got.

#495 Bump sushy-tools to include a fix for potential race
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#453 CI: add combined upgrade test case
  Makefile
  scripts/feature_tests/setup_env.sh
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, size/L

#474 Upgrade test document updates
  scripts/feature_tests/README.md
Labels: approved, lgtm, size/M

#492 Update Fedora CoreOS image version
  01_prepare_host.sh
  lib/images.sh
Labels: approved, lgtm, size/S

#498 Fetch the latest Cluster API release
  lib/releases.sh
Labels: approved, lgtm, size/S

#497 CI: fix upgrade test nits
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/S

#499 CI: Remove sourcing of common.sh script
  lib/releases.sh
Labels: approved, lgtm, size/XS

#501 Update k8sversion to 1.18.8
  config_example.sh
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#478 Update the clouds.yaml generation to include http basic auth and tls
  03_launch_mgmt_cluster.sh
  clouds.yaml.j2
  clouds.yaml.template
  config_example.sh
  host_cleanup.sh
  lib/common.sh
  lib/network.sh
  vars.md
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: approved, lgtm, size/L

#505 🌱 Update kustomize and kind versions to latest
  lib/common.sh
Labels: approved, lgtm, size/XS

#506 Change erroneous Ubuntu Node Image
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#509 Create metal3 namespace for CAPM3-v1a3
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#507 Improve code readabilty and add/fix comments in lib/scripts
  lib/common.sh
  lib/images.sh
  lib/network.sh
  lib/releases.sh
Labels: approved, lgtm, size/M

#510 Refactor metal3-dev-env to accomodate BMO changes
  03_launch_mgmt_cluster.sh
  04_verify.sh
Labels: approved, lgtm, size/M

#511 Fix namespace for baremetal-operator-controller-manager
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#512 fix small comment issue
  01_prepare_host.sh
Labels: approved, lgtm, ok-to-test, size/XS

#513 Bump python version to 3.9
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#514 Add condition for moving BMO kustomization files in v1alpha4
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#515 By default, use Ubuntu 20.04 for target nodes
  lib/common.sh
Labels: approved, lgtm, ok-to-test, size/XS

#508 🌱 Enable TLS and Basic auth after pivoting
  03_launch_mgmt_cluster.sh
  lib/ironic_basic_auth.sh
  lib/ironic_tls_setup.sh
  scripts/feature_tests/cleanup_env.sh
  scripts/run.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#516 Follow-up to #508
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#517 🐛 Add kubeconfig when installing BMO and Ironic and change Ironic container name
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#518 Fix a minor bug
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, ok-to-test, size/XS

#519 🐛 Fix removing all ironic containers properly
  01_prepare_host.sh
  host_cleanup.sh
  lib/common.sh
Labels: approved, lgtm, size/S

#520 ✨ Enable IRONIC_FAST_TRACK feature for CentOS
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#493 Upgrade pivoting test
  scripts/feature_tests/pivoting/Makefile
Labels: approved, lgtm, size/XS

#523 Fix/remove small comment issues
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  04_verify.sh
  cluster_cleanup.sh
  hack/run-bmo-loop.sh
  lib/ironic_basic_auth.sh
  lib/ironic_tls_setup.sh
  lib/releases.sh
Labels: approved, lgtm, size/M

#526 🐛 Fix referencing to deleted "provision_host.sh" script
  config_example.sh
  vars.md
Labels: approved, lgtm, size/S

#527 ✨ Add nodeDrainTimeout for controlplane and worker template in metal3-dev-env.
  config_example.sh
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#530 Fix repetition inside condition
  lib/releases.sh
Labels: approved, lgtm, size/S

#533 Don't clone Cluster API
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/releases.sh
Labels: approved, lgtm, size/XS

#535 CI: upgrade common code updates
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, size/L

#532 Set default CAPM3_VERSION to v1alpha4
  config_example.sh
Labels: approved, lgtm, ok-to-test, size/XS

#537 Add local ironic container re-create instructions
  README.md
  lib/ironic_basic_auth.sh
  lib/ironic_tls_setup.sh
Labels: approved, lgtm, size/M

#538 Add pivot and repivot in normal CI tests
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#534 🌱 Parametrize ironic ports
  03_launch_mgmt_cluster.sh
  clouds.yaml.j2
  lib/network.sh
  lib/releases.sh
  vm-setup/roles/firewall/defaults/main.yml
Labels: approved, lgtm, size/M

#539 📖 Update vars.md with ports
  lib/network.sh
  vars.md
Labels: approved, lgtm, size/S

#541 🌱 Use latest version of Ansible
  01_prepare_host.sh
  centos_install_requirements.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#540 Fix BMOPATH in ansible
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#542 Fix BMO PATH in move_back.yaml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
Labels: approved, lgtm, size/XS

#543 Update the local images if the *LOCAL_IMAGE* exported
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/M
