Repository metal3-io/metal3-dev-env, pull requests merged in 2020-04, with the labels that each got.

#279 Remove nodes_file on tear down
  host_cleanup.sh
  vm-setup/roles/libvirt/tasks/main.yml
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
  vm-setup/roles/libvirt/tasks/vm_teardown_tasks.yml
Labels: approved, lgtm, size/XS

#278 Fix target nodes networking setup
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
Labels: approved, lgtm, size/S

#273 Freeze the version of kubelet, kubectl and kubeadm
  config_example.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#283 Add exception for missing double quotes
  01_prepare_host.sh
  02_configure_host.sh
Labels: approved, lgtm, size/XS

#282 Replace old baremetal provider name references with metal3
  config_example.sh
Labels: approved, lgtm, size/XS

#277 Kind cluster support added as option for minikube
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  Makefile
  cluster_cleanup.sh
  lib/common.sh
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: approved, lgtm, ok-to-test, size/L

#289 Install python3 in CentOS target cluster and use dnf
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
Labels: approved, size/S

#290 Change Kubeconfig path in tests to reflect the username
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/XS

#291 :bug: ambiguous if statement in kind condition
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#280 Add optional dual-stack baremetal network support
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/network.sh
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
  vm-setup/roles/libvirt/templates/network.xml.j2
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, size/L

#267 Switch sushy-tools to bind to "::"
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#293 Kind access to local Docker registry made possible by using containerd config
  03_launch_mgmt_cluster.sh
  lib/common.sh
  vm-setup/roles/firewall/defaults/main.yml
Labels: approved, lgtm, size/S

#292 Remove v1alpha1 and v1alpha2 versions of CAPM3
  03_launch_mgmt_cluster.sh
  04_verify.sh
  05_test_v1alpha1.sh
  Makefile
  README.md
  README_v1alphaX.md
  config_example.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/XL

#281 Upgrade kubernetes version to v1.18.0
  config_example.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#299 Add missing privilege to run docker and kind commands
  03_launch_mgmt_cluster.sh
  centos_install_requirements.sh
  cluster_cleanup.sh
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#297 Replace CAPI and CAPM3 deployment with clusterctl in metal3-dev-env
  03_launch_mgmt_cluster.sh
  host_cleanup.sh
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_worker.yml
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/provision_worker.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/kustomization.yaml
  vm-setup/roles/v1aX_integration_test/templates/kustomization_empty.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XL

#301 :bug: CAPM3BRANCH type wrongly mixed with CAPM3 release version
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S
