Repository metal3-io/metal3-dev-env, pull requests merged in 2020-11, with the labels that each got.

#544 Fix v1a3 pivot workflow
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/S

#547 Advance sushy-tools to 0.12.1
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#549 Optimize small code part
  host_cleanup.sh
Labels: approved, lgtm, ok-to-test, size/S

#528 Set CAPI_VERSION to fixed v1alpha3
  lib/common.sh
Labels: approved, lgtm, ok-to-test, size/S

#551 Add fetch manifest script to the feature tests.
  scripts/feature_tests/pivoting/Makefile
Labels: approved, lgtm, size/XS

#554 Fix ironic configmap for TLS
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#552 Set default BMC_DRIVER to "mixed"
  config_example.sh
Labels: approved, lgtm, ok-to-test, size/XS

#553 Allow enabling secure boot for testing VMs
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: approved, lgtm, size/XS

#555 Fix serial log deletion
  host_cleanup.sh
Labels: approved, lgtm, size/XS

#524 Implementation for 3 control planes and 1 worker upgrade automated test after pivoting.
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/L

#550 CI: count workers in target cluster that are 'Ready'
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/XS

#525 Enable TLS between Ironic and Mariadb
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/ironic_tls_setup.sh
  vars.md
Labels: approved, lgtm, size/M

#556 Clean up logwatch containers
  lib/common.sh
Labels: approved, lgtm, size/XS

#557 🐛 Fix leftover comment
  ubuntu_install_requirements.sh
Labels: approved, lgtm, size/XS

#558 Remove ironic-log and inspector-log in move
  scripts/feature_tests/cleanup_env.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/XS

#559 Deactivate combined upgrade test use case for Centos.
  scripts/feature_tests/upgrade/upgrade.sh
Labels: approved, lgtm, size/XS

#561 Migrate ubuntu_install_req*.sh from bash to Ansible
  01_prepare_host.sh
  ubuntu_install_requirements.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/files/daemon.json
  vm-setup/roles/packages_installation/tasks/main.yml
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: approved, lgtm, size/L

#564 Fix indentation for the podman installation
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: approved, lgtm, size/S

#565 Couple of fixes related to #561
  01_prepare_host.sh
  lib/network.sh
  vm-setup/roles/packages_installation/files/daemon.json
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: approved, lgtm, size/M
