Repository metal3-io/metal3-dev-env, pull requests merged in 2020-02, with the labels that each got.

#202 Fix when kubectl already installed and it is not latest
  01_prepare_host.sh
Labels: approved, lgtm, ok-to-test, size/S

#188 Fix locale issue when checking for XFS compatibility
  lib/common.sh
Labels: approved, lgtm, ok-to-test, size/XS

#209 Add missing variables to v1alpha1 example
  scripts/v1alpha1/create_machine.sh
Labels: approved, lgtm, ok-to-test, size/XS

#210 Add missing sshd to the Ubuntu installation
  ubuntu_install_requirements.sh
Labels: approved, lgtm, ok-to-test, size/XS

#207 Make code python 3 compatible
  vm-setup/library/generate_macs.py
Labels: approved, lgtm, ok-to-test, size/XS

#212 Specify cloning directory
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#194 Maintain Ironic Endpoint with Keepalived
  03_launch_mgmt_cluster.sh
  config_example.sh
  crs/v1alpha2/cluster.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  lib/common.sh
  lib/network.sh
  scripts/v1alpha2/create_cluster.sh
Labels: approved, lgtm, size/M

#217 CAPBMBRANCH set to master
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#219 README update
  README.md
Labels: approved, lgtm, size/XS

#216 Ansible changes to have a single source of CRs
  05_test_v1aX.sh
  crs/v1alpha2/cluster.yaml
  crs/v1alpha2/controlplane_centos.yaml
  crs/v1alpha2/controlplane_ubuntu.yaml
  crs/v1alpha2/workers_centos.yaml
  crs/v1alpha2/workers_ubuntu.yaml
  crs/v1alpha3/cluster.yaml
  crs/v1alpha3/controlplane_centos.yaml
  crs/v1alpha3/controlplane_ubuntu.yaml
  crs/v1alpha3/workers_centos.yaml
  crs/v1alpha3/workers_ubuntu.yaml
  lib/common.sh
  scripts/v1alphaX/create_cluster.sh
  scripts/v1alphaX/create_controlplane.sh
  scripts/v1alphaX/create_worker.sh
  scripts/v1alphaX/delete_cluster.sh
  scripts/v1alphaX/delete_controlplane.sh
  scripts/v1alphaX/delete_worker.sh
  scripts/v1alphaX/deprovision_cluster.sh
  scripts/v1alphaX/provision_cluster.sh
  vm-setup/roles/v1aX_integration_test/tasks/deprovision.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/pause.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XXL

#226 Fix v1a3 verification
  04_verify.sh
Labels: approved, lgtm, size/S

#215 Make installing openstack/ironic clients optional
  .gitignore
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  centos_install_requirements.sh
  lib/common.sh
  openstackclient.sh
  vbmc.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/teardown_tasks.yml
Labels: approved, lgtm, size/M

#230 Add missing 'netplan apply' command in ubuntu CRs
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml
Labels: approved, lgtm, size/XS

#228 Include tasks to download centos-updated.qcow2 & some Ansible vars modifications
  vm-setup/roles/v1aX_integration_test/tasks/provision.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, ok-to-test, size/S

#231 use NODES_FILE to manage where the nodes file is written
  02_configure_host.sh
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
Labels: approved, lgtm, size/XS

#223 Add CentOS 8 support
  02_configure_host.sh
  centos_install_requirements.sh
  lib/common.sh
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: approved, lgtm, size/M

#220 Clean RDO repos on RHEL/CentOS
  centos_install_requirements.sh
Labels: approved, lgtm, size/XS

#233 Do not install Docker on CentOS8
  centos_install_requirements.sh
  ip_range_check.py
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, size/M

#235 Modify templates to deploy control plane with CAKCP in v1alpha3
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#234 Allow customization of hostnames for nodes
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, ok-to-test, size/XS

#214 Use python3 to build ubuntu based Metal3-dev-env
  lib/network.sh
  ubuntu_install_requirements.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: approved, lgtm, size/S

#236 Add validation to ignore 404 when object is not found
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_cluster.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_controlplane.yml
  vm-setup/roles/v1aX_integration_test/tasks/deprovision_worker.yml
Labels: approved, lgtm, size/S
