Repository metal3-io/metal3-dev-env, pull requests merged in 2021-07, with the labels that each got.

#707 ✨Drop CentOS8.3 and move to CentOS Stream
  01_prepare_host.sh
  README.md
  config_example.sh
  lib/common.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#714 remove dhellmann from owners
  OWNERS
Labels: approved, lgtm, size/XS

#716 Check NUM_NODES before creating VMs
  lib/common.sh
  scripts/feature_tests/upgrade/Makefile
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, size/S

#723 Add furkatgofurov7 as approver
  OWNERS
Labels: approved, lgtm, size/XS

#720 Non-TLS support for metal3-dev-env.
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#725 🐛 Fix feature tests
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
  scripts/feature_tests/feature_test_vars.sh
Labels: approved, lgtm, size/S

#722 Upgrade Ansible k8s modules to 2.1.1
  vm-setup/requirements.yml
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: approved, lgtm, size/S

#727 Clean up sushy-tools and vbmc Dockerfiles
  resources/sushy-tools/Dockerfile
  resources/vbmc/Dockerfile
Labels: approved, lgtm, size/S

#719 use /usr/bin/python3 for Ansible
  vm-setup/inventory.ini
Labels: approved, lgtm, size/XS

#718 Improve/tidy up feature test related scripts and notes
  scripts/feature_tests/README.md
  scripts/feature_tests/cleanup_env.sh
Labels: approved, lgtm, size/S

#695 Refactor ironic upgrade to avoid shell
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#730 Set namespace in the Metal3DataTemplate template
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: approved, lgtm, size/XS

#729 Make Ironic credential available in CAPM3 e2e tests.
  scripts/run_command.sh
Labels: approved, lgtm, size/XS

#731 Use kubernetes.core module for Ansible
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/M

#733 Decrease delay when waiting for reboot
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/XS

#721 Deploy BMO outside of CAPM3 in metal3-dev-env
  03_launch_mgmt_cluster.sh
  04_verify.sh
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#734 Fix PR 721 comments
  lib/common.sh
Labels: approved, lgtm, size/XS

#690 Refactor upgrade for control plane components
  .gitignore
  vm-setup/roles/v1aX_integration_test/filter_plugins/__init__.py
  vm-setup/roles/v1aX_integration_test/filter_plugins/k8s_fields.py
  vm-setup/roles/v1aX_integration_test/filter_plugins/k8s_fields_test.py
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/capm3-clusterctl-settings.json
  vm-setup/roles/v1aX_integration_test/templates/cluster-api-clusterctl-settings.json
Labels: approved, lgtm, size/L

#679 Replace node_reuse shells by k8s and k8s_info modules
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
Labels: approved, lgtm, size/XL

#710 Replace remediation test shells with ansible modules
  vm-setup/roles/v1aX_integration_test/filter_plugins/template.py
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/XL

#692 Cleanup variables for CAPI and CAPM3
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/templates/Metal3MachineTemplate.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#735 Add ansible profile_tasks callback to print tasks timing
  ansible.cfg
  scripts/run.sh
Labels: approved, lgtm, size/XS

#736 Refactor pending shells using ansible k8s module in integration_test role
  vm-setup/roles/v1aX_integration_test/tasks/inspection.yml
  vm-setup/roles/v1aX_integration_test/tasks/post_pivot.yml
  vm-setup/roles/v1aX_integration_test/tasks/power_cycle.yml
Labels: approved, lgtm, size/L

#732 Add k8s, ansible, kind node to renovate config
  renovate.json
Labels: approved, lgtm, size/L

#738 Decrease delay when waiting for node to be NotReady
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/XS

#693 ⚠️Modify metal3-dev-env for CAPI v1alpha4 changes
  03_launch_mgmt_cluster.sh
  04_verify.sh
  lib/common.sh
  lib/releases.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#742 Switch order of BMO and cluster api creation
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#747 Follow-up to 693
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#696 Refactor upgrade tests for k8s
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: approved, lgtm, size/L

#746 Ignore minikube flaky issue
  lib/common.sh
Labels: approved, lgtm, size/S

#748 Fetch Ironic container logs before pivoting
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/M

#744 Set default value of FORCE_REPO_UPDATE to true
  lib/common.sh
  vars.md
Labels: approved, lgtm, size/XS

#749 Install BMO after cluster init is completed in the target cluster
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/S
