Repository metal3-io/metal3-dev-env, pull requests merged in 2021-02, with the labels that each got.

#592 Add post pivot operation
  scripts/feature_tests/pivoting/pivot.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/post_pivot.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#594 Fix interface ironicendpoint is missing in centos
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
Labels: approved, lgtm, ok-to-test, size/XS

#598 Change k8s to 1.20.0
  config_example.sh
  lib/common.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#590 K8s version upgrade from 1.20.0 to 1.20.2 for upgrade workflow.
  scripts/feature_tests/upgrade/upgrade_common.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/S

#600 Fix ansible firewalld module
  vm-setup/roles/firewall/tasks/firewalld.yaml
Labels: approved, lgtm, size/S

#601 Add verify action during post pivot action
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XS

#603 Uplifting k8s version to 1.20.2
  config_example.sh
  lib/common.sh
  lib/images.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#602 Bump the Golang version to 1.16
  vm-setup/install-package-playbook.yml
Labels: approved, lgtm, size/XS

#604 Modify default_vcpu and use minimum resources in metal3-dev-env
  vm-setup/roles/common/defaults/main.yml
Labels: approved, lgtm, size/XS
