Repository metal3-io/metal3-dev-env, pull requests merged in 2021-10, with the labels that each got.

#815 CAPI componets upgrade from v0.4.1 to v0.4.2 for upgrade workflow
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: size/XS, approved, lgtm

#801 Bugfix pull image if missing bash function
  01_prepare_host.sh
  lib/common.sh
Labels: size/XS, approved, lgtm

#803 Add Docker registry to Renovate
  lib/common.sh
  renovate.json
Labels: size/S, approved, lgtm

#817 Generate clusterctl binary with latest CAPI release in upgrade workflow
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/XS, approved, lgtm

#816 Pretty print Ansible failure JSON
  ansible.cfg
Labels: size/XS, approved, lgtm

#818 🐛 Fix image pulling for podman
  lib/common.sh
Labels: size/S, approved, lgtm

#809 Add a bash script that only generates the cluster templates
  scripts/generate-template.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#812 Do not verify TLS in sushy-tools, real hardware doesn't do it
  vm-setup/roles/virtbmc/defaults/main.yml
Labels: size/XS, approved, lgtm

#779 ✨ Enhance Ansible retry logs
  ansible.cfg
Labels: size/S, approved, lgtm

#810 Handle 'available' state
  vm-setup/roles/v1aX_integration_test/filter_plugins/status.py
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/inspection.yml
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: size/M, approved, lgtm

#823 🐛Run upgrade tests with proper CAPM3 releases
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/S, approved, lgtm

#826 🐛 Fix clusterctl-settings path in upgrade test
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/S, approved, lgtm

#827 Install epel-release before anything else in centos
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#833 Add CAPM3 main branch references
  README.md
  config_example.sh
  lib/common.sh
  vars.md
Labels: size/S, approved, lgtm

#832 Clean up upgrade test
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/M, approved, lgtm

#835 ⚠️ Parameterize container image registry var
  config_example.sh
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#845 Add quay.io as the registry
  lib/common.sh
Labels: size/XS, approved, lgtm
