Repository metal3-io/metal3-dev-env, pull requests merged in 2021-08, with the labels that each got.

#759 Add Mohammed as reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#760 Don't try to delete non-existing httpd container
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/XS, approved, lgtm

#763 Update CAPM3RELEASE to point to v0.5.0
  lib/releases.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#750 Use baremetal operator branch image when deploying to target cluster
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/XS, approved, lgtm

#756 Separate k8s version variable for upgrade test
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: size/XS, approved, lgtm

#764 Parameterize resource API versions
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/S, approved, lgtm

#765 Don't restore BMO configmap until we deploy it in the target cluster
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/XS, approved, lgtm

#766 Fix node reuse tests
  lib/common.sh
  scripts/feature_tests/node_reuse/node_reuse.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#753 Clean when deleting minikube
  lib/common.sh
Labels: size/XS, approved, lgtm

#754 Update feature test notes
  scripts/feature_tests/README.md
Labels: size/S, approved, lgtm

#770 Remove post_pivot script for feature test
  scripts/feature_tests/pivoting/pivot.sh
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/post_pivot.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#776 Set cert-manager to v1.4.0
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#774 Add condition to enable/disable IPA download
  01_prepare_host.sh
  lib/common.sh
  vars.md
Labels: size/S, approved, lgtm
