Repository metal3-io/metal3-dev-env, pull requests merged in 2021-03, with the labels that each got.

#605 Fix openshift python package to 0.11.2
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: approved, lgtm, size/XS

#607 Reduce loop cycle time for upgrade script.
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/M

#574 Migrate centos_install_req*.sh from bash to Ansible
  01_prepare_host.sh
  centos_install_requirements.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/centos_required_packages.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: approved, lgtm, size/L

#606 Bump sushy-tools and allow to ignore boot device
  resources/sushy-tools/Dockerfile
  vm-setup/roles/virtbmc/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, size/XS

#609 Revert Bump sushy-tools and allow to ignore boot device to fix CI
  resources/sushy-tools/Dockerfile
  vm-setup/roles/virtbmc/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: size/XS

#608 Using a better lower-bound version for jinja2 to make sure behavior is right
  01_prepare_host.sh
Labels: approved, lgtm, ok-to-test, size/XS

#611 Support NUM_NODES=0 metal3 deployments
  03_launch_mgmt_cluster.sh
  04_verify.sh
  vm-setup/roles/common/tasks/main.yml
  vm-setup/roles/common/tasks/vm_nodes_tasks.yml
Labels: approved, lgtm, ok-to-test, size/S

#614 Uplift k8s to 1.20.4
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/common.sh
  lib/images.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#612 Move ironic upgrade tests to ubuntu based tests
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/M

#615 Fix kind node image version
  01_prepare_host.sh
Labels: approved, lgtm, size/XS

#617 Fix compatibility with newer ironic-client images
  openstackclient.sh
Labels: approved, lgtm, size/S

#619 Revert "Revert Bump sushy-tools and allow to ignore boot device
  resources/sushy-tools/Dockerfile
  vm-setup/roles/virtbmc/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, size/XS
