Repository metal3-io/metal3-dev-env, pull requests merged in 2021-06, with the labels that each got.

#677 Fix minikube start
  lib/common.sh
Labels: approved, lgtm, size/S

#678 Remove httpd-reverse-proxy from ironic container list
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: approved, lgtm, size/S

#660 Update cirros version to 0.5.2
  lib/images.sh
Labels: approved, lgtm, ok-to-test, size/XS

#682 🐛 Fix upgrade tests
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, size/XS

#585 Fix bare variable evaluation deprecation issue
  vm-setup/roles/libvirt/tasks/network_setup_tasks.yml
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
  vm-setup/roles/libvirt/tasks/vm_teardown_tasks.yml
Labels: approved, lgtm, ok-to-test, size/XS

#680 Remove CAPM3 v1alpha3 instances and modify v1alpha4 accordingly
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  config_example.sh
  lib/common.sh
  lib/releases.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
Labels: approved, lgtm, size/L

#667 Parameterize Ansible version
  01_prepare_host.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#684 🌱 Adapt metal3-dev-env to latest IPAM
  lib/common.sh
Labels: approved, lgtm, size/S

#685 Prepare metal-dev-env to incorporate CAPM3 v1alpha5 api
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  config_example.sh
  lib/common.sh
  lib/releases.sh
  scripts/feature_tests/README.md
  scripts/fetch_manifests.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#687 Fix CAPM3_LOCAL_RUN scale namespace bug
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#669 Refactor some usage of shell into native kubernetes modules + small fixes
  .gitignore
  01_prepare_host.sh
  vm-setup/roles/firewall/tasks/main.yml
  vm-setup/roles/libvirt/tasks/network_teardown_tasks.yml
  vm-setup/roles/packages_installation/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/L

#673 Move from CentOS8.3 to CentOS Stream
  01_prepare_host.sh
  02_configure_host.sh
  README.md
  lib/common.sh
Labels: approved, lgtm, size/S

#691 📖 Add v1a5 job badges and fixes to documentation
  README.md
  scripts/feature_tests/README.md
  vars.md
Labels: approved, lgtm, size/S

#676 🐛 Fix kubectl apply issue in nodereuse
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
Labels: approved, lgtm, size/XS

#661 Add an extra disk partition and mounting
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#694 Add renovate config with Minikube updates
  renovate.json
Labels: approved, lgtm, size/S

#672 Replace ansible shells by k8s_info module in the integration tests move tasks
  vm-setup/roles/v1aX_integration_test/filter_plugins/status.py
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/L

#699 Expand Renovate reviewers list
  renovate.json
Labels: approved, lgtm, size/S

#700 Add kind to Renovate managed dependencies
  renovate.json
Labels: approved, lgtm, size/XS

#701 Uplift k8s to 1.21.2
  README.md
  config_example.sh
  lib/common.sh
  lib/images.sh
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#697 Tidy variables in clusterctl templating
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/Metal3MachineTemplate.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-cluster.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers-kubeadm-config-ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-upgrade-test.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-vars.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XL

#704 Update notes from CentOS 8 Stream to CentOS 8.3
  README.md
Labels: approved, lgtm, size/XS

#705 Add Nam and Michael as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#703 Add a script to run a command with environment variables
  lib/images.sh
  lib/network.sh
  scripts/run_command.sh
  vars.md
Labels: approved, lgtm, size/M

#683 Add readiness check for BMO controller manager
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/S

#708 Verify existence of resources before filtering
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/S

#664 Bump kustomize version to latest
  lib/common.sh
Labels: approved, lgtm, size/XS

#599 Allow setting the lease expiry for DHCP
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, size/S

#709 Update DockerHub registry path
  hack/markdownlint.sh
  hack/shellcheck.sh
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#711 Switch to DIY callback plugin for Ansible
  01_prepare_host.sh
  02_configure_host.sh
  ansible.cfg
  host_cleanup.sh
  scripts/run.sh
Labels: approved, lgtm, size/M

#713 🐛 Remove duplicate manifest fetching for KCP
  scripts/fetch_manifests.sh
Labels: approved, lgtm, size/XS
