Repository metal3-io/metal3-dev-env, pull requests merged in 2021-11, with the labels that each got.

#840 Clarify BMC_DRIVER usage to include redfish-virtualmedia
  config_example.sh
  vars.md
Labels: size/XS, approved, lgtm

#851 disable cert verification in clouds.yaml.j2
  clouds.yaml.j2
Labels: approved, lgtm

#841 Make BOOT_MODE configurable
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/network.sh
  vars.md
Labels: size/S, approved, lgtm

#837 ⚠️ Adapt metal3-dev for CAPI v1beta1 API changes
  04_verify.sh
  README.md
  config_example.sh
  lib/common.sh
  lib/releases.sh
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#853 Add krew installation to 01 script
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#813 Tilt environment setup for metal3 controllers
  03_launch_mgmt_cluster.sh
  README.md
  cluster_cleanup.sh
Labels: size/M, approved, lgtm

#856 ✨ Test local images properly when using container images from Nordix registry
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: size/S, approved, lgtm

#858 Fix BMO CRDs labelling
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/XS, approved, lgtm

#848 Allow creating VMs with emulated TPM device
  vars.md
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/M, approved, lgtm, ok-to-test

#861 Uplift Kubernetes version to 1.22.3
  config_example.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#863 Print commands as they are executed during fetch_manifests.sh
  scripts/fetch_manifests.sh
Labels: size/XS, approved, lgtm

#866 Don't start fetching CRs until M3Machine status is rebuilt
  05_test.sh
Labels: size/XS, approved, lgtm

#865 Follow up to uplift k8s verion variable to 1.22.3
  lib/common.sh
  scripts/feature_tests/feature_test_vars.sh
  vars.md
Labels: size/XS, approved, lgtm, do-not-merge/hold

#871 Remove stbenjam from OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#849 Add support for DEPLOY_ISO_URL
  03_launch_mgmt_cluster.sh
  lib/network.sh
Labels: approved, lgtm

#873 Pin calico version to v3.21.0
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#874 Add kubernetes pip dependecy handling to renovate
  renovate.json
Labels: size/S, approved, lgtm

#876 Fetch container logs before pivoting when it is minikube cluster
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/M, approved, lgtm

#852 Add configurable support for additional networks
  vars.md
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/common/tasks/extra_networks_tasks.yml
  vm-setup/roles/common/tasks/main.yml
Labels: size/L, approved, lgtm

#860 Update the feature test README regarding v1beta1 migration
  scripts/feature_tests/README.md
Labels: size/XS, approved, lgtm
