Repository metal3-io/metal3-dev-env, pull requests merged in 2021-04, with the labels that each got.

#621 Remove undeclared WORKER_MACHINE_COUNT variable
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: approved, lgtm, size/XS

#620 Parameterize CAPI maxSurge field
  config_example.sh
  lib/common.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#627 Fix missing upgrade vars in feature tests
  Makefile
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, ok-to-test, size/S

#630 Upgrade to k8s 1.21
  scripts/feature_tests/upgrade/upgrade_common.sh
Labels: approved, lgtm, size/XS

#631 Add travis file
  .travis.yml
Labels: approved, lgtm, size/S

#616 Move controlplane components upgrade to ubuntu based test
  lib/releases.sh
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: approved, lgtm, size/L

#625 replace curl with wget to download images.
  01_prepare_host.sh
Labels: approved, lgtm, ok-to-test, size/XS

#636 🐛 Fix the issue that tripleo-repo requires a stream version of OS to run properly.
  resources/vbmc/Dockerfile
Labels: approved, lgtm, size/S

#635 Remove libvirtd restart in init_minikube
  lib/common.sh
Labels: approved, lgtm, size/XS

#639 Make pivot and repivot separate in feature test
  Makefile
  scripts/feature_tests/pivoting/Makefile
Labels: size/XS

#638 🐛 A proper fix for the Centos stream issue that tripleo-repo requires a stream version of OS to run properly
  resources/vbmc/Dockerfile
Labels: size/XS
