Repository metal3-io/metal3-dev-env, pull requests merged in 2021-09, with the labels that each got.

#772 ⚠️ Run upgrade test with latest API versions
  scripts/feature_tests/README.md
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-api-clusterctl-settings.json
Labels: size/L, approved, lgtm

#782 Bump Golang to 1.16.7, fix cert manager ca injection bug and remove hard-coding cert-manager version
  03_launch_mgmt_cluster.sh
  vm-setup/install-package-playbook.yml
Labels: size/S, approved, lgtm

#751 Automate selecting CAPI version based on CAPM3
  README.md
  lib/common.sh
Labels: size/S, approved, lgtm

#648 Add support for external VLAN in integration tests
  config_example.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/filter_plugins/bmh_metadata.py
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/metal3datatemplate-template.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/L, approved, lgtm

#785 Fix bug in node reuse where BMHs are not found
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#767 Uplift k8s to 1.22.0
  config_example.sh
  lib/common.sh
  scripts/feature_tests/node_reuse/node_reuse.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#771 Refactor upgrade test by removing unnecessary resource scaling
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/M, approved, lgtm

#788 chdir into BMOPATH when using deploy.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
Labels: size/XS, approved, lgtm

#787 BugFix: Download upgraded image and add variables to M3M template.
  vm-setup/roles/v1aX_integration_test/tasks/download_image.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#791 Optimize upgrade script.
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/S, approved, lgtm

#792 Refactor download_image.yaml
  vm-setup/roles/v1aX_integration_test/tasks/download_image.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, lgtm

#784 Add Ironic endpoints checks
  04_verify.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/S, approved, lgtm

#789 Add ansible verbosity to default level
  host_cleanup.sh
  scripts/run.sh
Labels: size/XS, approved, lgtm

#800 Pull container images only if missing
  01_prepare_host.sh
  lib/common.sh
Labels: size/S, approved, lgtm

#802 Remove Jaakko-Os from OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#793 Fix node reuse test with upgraded image
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/node_reuse/node_reuse.sh
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/Metal3MachineTemplate.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/L, approved, lgtm

#804 Use kubectl instead of k8s module for applying
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#797 Remove hack to override IPAM cert name
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#806 Remove ironic-inspector-log-watch
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/XS, approved, lgtm

#798 Enable authentication in sushy-tools
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/virtbmc/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: size/S, approved, lgtm

#807 Disable deployment of controllers in tilt environment
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#808 Use shell instead of k8s_info when KCP is unstable
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: size/S, approved, lgtm

#805 Add git configuration options for BMO
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#811 Uplift minikube to 1.23.2 for v1a5 tests
  lib/common.sh
Labels: size/XS, approved, lgtm

#814 Fix minikube download for v1a4
  01_prepare_host.sh
Labels: size/XS, approved, lgtm
