Repository metal3-io/metal3-dev-env, pull requests merged in 2021-12, with the labels that each got.

#839 Support build ironic-image from source
  02_configure_host.sh
  config_example.sh
Labels: size/S, approved, lgtm

#855 🐛 Refactor node reuse testing
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
Labels: size/L, approved, lgtm

#884 Uplift go 1.17.5
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm

#882 Include CAPI repo to the list of cloned repos
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/releases.sh
Labels: size/XS, approved, lgtm

#886 Add a variable for mariadb-image
  lib/common.sh
Labels: size/XS, approved, lgtm

#868 Enable TLS and basic authentication in tilt environment
  03_launch_mgmt_cluster.sh
  cluster_cleanup.sh
  scripts/deploy_tilt_env.sh
Labels: size/L, approved, lgtm

#870 Modify BMO Branch reference to main branch
  03_launch_mgmt_cluster.sh
  README.md
  config_example.sh
  lib/common.sh
  vars.md
Labels: size/S, approved, lgtm

#889 Use CAPI prerelease v1.1.0-beta.1
  lib/releases.sh
Labels: size/XS, approved, lgtm

#864 Migrate upgrade tests to v1beta1 APIs + Point mariadb container spec to the separate image.
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  scripts/run.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-upgrade-test.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#893 Remove 'master' reference
  05_test.sh
  config_example.sh
  lib/common.sh
  scripts/feature_tests/README.md
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/node_reuse/Makefile
  scripts/feature_tests/pivoting/Makefile
  scripts/feature_tests/pivoting/upgrade.sh
  scripts/feature_tests/remediation/Makefile
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-vars.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/L, approved, lgtm

#892 Support proxy for Docker Hub
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  scripts/deploy_tilt_env.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm
