Repository metal3-io/metal3-dev-env, pull requests merged in 2021-01, with the labels that each got.

#529 Cached images are stored in http://$PROVISIONING_URL_HOST/images/
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, ok-to-test, size/XS

#582 Update sushy-tools to 0.14.0
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#584 Fix small typo
  01_prepare_host.sh
Labels: approved, lgtm, ok-to-test, size/XS

#586 Add risk reduction for DNSpooq by setting libvirt cache-size=0
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: approved, lgtm, size/XS

#581 Use Kubernetes latest release 1.20
  config_example.sh
  lib/common.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc
  vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#589 Fix basic_aut credentials vars of inspector
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#588 Migrate to Kind v0.10.0
  lib/common.sh
Labels: approved, lgtm, size/XS

#591 Uplift k8s to 1.20.2 and Fix a small bug in kubelet args
  config_example.sh
  lib/common.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M
