Repository metal3-io/metal3-dev-env, pull requests merged in 2021-05, with the labels that each got.

#647 Tidy Calico config in integration test verify
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/XS

#628 Add m3dt Template Reference feature test
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
Labels: approved, lgtm, size/M

#634 Replace upgrade shell script by ansible
  scripts/feature_tests/upgrade/Makefile
  scripts/feature_tests/upgrade/upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/files/workload.yaml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/templates/Metal3MachineTemplate.yml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/XL

#651 Remove unused upgrade bash scripts
  scripts/feature_tests/README.md
  scripts/feature_tests/upgrade/1cp_1w_bootDiskImage_cluster_upgrade.sh
  scripts/feature_tests/upgrade/README.md
  scripts/feature_tests/upgrade/clean_setup_env.sh
  scripts/feature_tests/upgrade/combined_tests/1cp_1w_bootDiskImageANDK8sControllers_clusterLevel_upgrade.sh
  scripts/feature_tests/upgrade/controlplane_components_upgrade/upgrade_CAPI_and_CAPM3_with_clusterctl.sh
  scripts/feature_tests/upgrade/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
  scripts/feature_tests/upgrade/upgrade_common.sh
  scripts/feature_tests/upgrade/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
Labels: approved, lgtm, size/XXL

#650 Re-arrange pivot script and add checks for cert-manager pods.
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: approved, lgtm, size/S

#652 Uplift minikube version to v1.20.0
  lib/common.sh
Labels: approved, lgtm, size/XS

#653 Add kashifest as approver
  OWNERS
Labels: approved, lgtm, size/XS

#657 Allow non-verified HTTPS sources for virtualmedia
  vm-setup/roles/virtbmc/defaults/main.yml
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: approved, lgtm, ok-to-test, size/XS

#629 Uplift to k8s 1.21.0
  config_example.sh
  lib/common.sh
  lib/images.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#658 Uplift kind node image and kind binary
  01_prepare_host.sh
  lib/common.sh
Labels: approved, lgtm, size/XS

#633 Create feature test for scale-in and node reuse
  Makefile
  config_example.sh
  lib/common.sh
  scripts/feature_tests/README.md
  scripts/feature_tests/node_reuse/Makefile
  scripts/feature_tests/node_reuse/node_reuse.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/L

#662 Update image/*location with upgraded k8s version notes
  vars.md
Labels: approved, lgtm, size/XS

#659 Allow the ironic container to restart when certificates are updated
  03_launch_mgmt_cluster.sh
  lib/common.sh
  vars.md
Labels: approved, lgtm, size/XS

#670 Parameterizes node image related variables to allow latest k8s version usage
  config_example.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/S

#663 Improve scale-in and node reuse feature tests
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
Labels: approved, lgtm, size/M

#665 Uplift to k8s 1.21.1
  config_example.sh
  lib/common.sh
  scripts/feature_tests/feature_test_provisioning.sh
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/inspection_test.sh
  scripts/feature_tests/node_reuse/node_reuse.sh
  scripts/feature_tests/remediation/remediation.sh
  scripts/feature_tests/setup_env.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#655 Modify ironic deployment name and namespace from pivoting and upgrading.
  lib/common.sh
  scripts/feature_tests/cleanup_env.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/move_back.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: approved, lgtm, size/M

#675 Fix minikube
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
Labels: approved, lgtm, size/XS

#637 Point ironic-inspector to the ironic image in quay
  lib/common.sh
  scripts/feature_tests/README.md
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: approved, lgtm, size/S
