Repository metal3-io/metal3-dev-env, pull requests merged in 2022-09, with the labels that each got.

#1069 Uplift ubuntu to 22.04
  lib/images.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
  tests/roles/run_tests/tasks/upgrade.yml
  tests/roles/run_tests/vars/main.yml
Labels: size/S, approved, lgtm

#1070 Upgrade k8s from v1.23.8 instead of v1.24.0
  tests/feature_tests/feature_test_vars.sh
Labels: size/XS, approved, lgtm

#1073 Fix commands for running keepalived monitor
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
Labels: size/XS, approved, lgtm

#1072 Add BMORELEASE as the default BMOBRANCH
  lib/common.sh
  lib/releases.sh
  vars.md
Labels: size/S, approved, lgtm

#1076 Improve the local image branch config
  02_configure_host.sh
  vars.md
Labels: size/M, approved, lgtm

#1061 Generate templates in tests folder
  Makefile
  tests/roles/run_tests/vars/main.yml
  tests/test.sh
Labels: size/XS, approved, lgtm

#1077 🌱 Add release-1.2 CAPM3/IPAM branch logic in scripts
  README.md
  lib/common.sh
  lib/releases.sh
  tests/feature_tests/upgrade/upgrade_vars.sh
  tests/roles/run_tests/tasks/upgrade.yml
Labels: size/S, approved, lgtm

#1082 Delete only the Cluster when cleaning up
  tests/roles/run_tests/tasks/main.yml
  tests/roles/run_tests/vars/main.yml
Labels: size/M, approved, lgtm

#1083 Improve metal3-dev-env repository cloning
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  vars.md
Labels: size/L, approved, lgtm
