Repository metal3-io/metal3-dev-env, pull requests merged in 2022-10, with the labels that each got.

#1084 improve local build of CAPI,CAPM3,IPAM,BMO
  02_configure_host.sh
  lib/common.sh
  vars.md
Labels: size/L, approved, lgtm

#1087 Add extra tag to locally built images
  02_configure_host.sh
Labels: size/XS, approved, lgtm

#1088 Improve local ironic image building
  02_configure_host.sh
  lib/common.sh
  vars.md
Labels: size/M, approved, lgtm

#1081 Bump k8s version and kind/node image version to v1.25.2
  config_example.sh
  lib/common.sh
  renovate.json
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
  tests/roles/run_tests/tasks/verify.yml
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1080 bug host_cleanup.sh: Make baremetal net deletion in Centos optional
  host_cleanup.sh
Labels: size/XS, approved, lgtm

#1093 🐛 Workaround NetworkManager issue
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#1091 Remove fmuyassarov from renovate assignee
  renovate.json
Labels: size/XS, approved, lgtm

#1094 Pin cert manager to v1.10.0 in the CI
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm
