Repository metal3-io/metal3-dev-env, pull requests merged in 2022-03, with the labels that each got.

#949 For BMC_Driver set to mixed, configure extra workers using redfish
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: size/XS, approved, lgtm

#958 allow kubectl caching after cluster creation
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
Labels: size/XS, approved, lgtm, ok-to-test

#897 Replace master branch reference with main
  02_configure_host.sh
  renovate.json
  scripts/feature_tests/healthcheck/Makefile
Labels: size/XS, approved, lgtm

#959 🌱 Remove ironic container workarounds in upgrade and pivoting tests
  scripts/feature_tests/README.md
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/M, approved, lgtm

#964 Convert IMAGE_OS string to lowercase before proceeding
  lib/images.sh
Labels: size/XS, approved, lgtm

#966 Update default minikube version to 1.25.2
  lib/common.sh
Labels: size/XS, approved, lgtm

#970 let Tilt handle image tag changing process.
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#972 Remove the "Management cluster forced to be minikube" message
  lib/common.sh
Labels: size/XS, approved, lgtm

#968 Update k8s, minikube and kind dependencies
  config_example.sh
  lib/common.sh
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#974 Make sure jq is installed before common.sh is sourced
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#950 Support CentOS Stream 9
  01_prepare_host.sh
  02_configure_host.sh
  lib/common.sh
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: size/M, approved, lgtm
