Repository metal3-io/metal3-dev-env, pull requests merged in 2022-06, with the labels that each got.

#1018 Downgrade to Ubuntu 20.04 and Disable kvm tdp_mmu for broken pipe issue
  01_prepare_host.sh
  lib/images.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#1022 Add cdrom for booting from virtual media
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: size/XS, approved, lgtm

#1023 Use firewalld with all centos distros
  lib/common.sh
Labels: size/XS, approved, lgtm

#824 Create provider-id by combining bmh and metal3machine resources
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: size/S, approved, lgtm, lifecycle/stale

#1025 Uplift CAPI version to 1.1.4 and CAPM3 version to 1.1.2
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#1029 Fetch HardwareData YAMLs as part of manifests fetching
  scripts/fetch_manifests.sh
Labels: size/XS, approved, lgtm

#1031 Update renovate configuration
  renovate.json
Labels: size/L, approved, lgtm

#1013 Do not check for passwordless sudo if running as root
  lib/common.sh
Labels: size/S, approved, lgtm, ok-to-test
