Repository metal3-io/metal3-dev-env, pull requests merged in 2022-12, with the labels that each got.

#1085 Remove CAPM3 release-0.5 branch check from _vars.sh scripts
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
Labels: size/S, approved, lgtm

#1119 markdown: pin mdl to 0.12.0 and fix complaints
  hack/markdownlint.sh
  tests/feature_tests/README.md
Labels: size/M, approved, lgtm

#1120 Add release-1.3 CAPM3/IPAM branch logic
  README.md
  lib/common.sh
Labels: size/XS, approved, lgtm

#1124 Bump BMO to release 0.2.x
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1125 shellcheck: pin shellcheck to v0.9.0
  01_prepare_host.sh
  04_verify.sh
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#1123 Update dependency ansible to v7.1.0
  lib/common.sh
Labels: size/XS, approved, lgtm

#1126 bind registry to EXTERNAL_SUBNET_V4_HOST
  02_configure_host.sh
Labels: size/XS, approved, lgtm

#1129 Fix BMO Local image building var naming
  lib/common.sh
Labels: size/XS, approved, lgtm

#1131 Configure vlan interface in centos when EXTERNAL_VLAN_ID is set
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
Labels: size/M, approved, lgtm
