Repository metal3-io/metal3-dev-env, pull requests merged in 2022-05, with the labels that each got.

#990 Fix an invalid Renovate configuration
  renovate.json
Labels: size/XS, approved, lgtm

#1001 Move BMH cleanup tasks to main.yaml
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
Labels: size/M, approved, lgtm

#969 Add CAPI labels on hardwareData CRD to pivot
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/S, approved, lgtm

#993 Update Ansible dependency to v5
  lib/common.sh
Labels: size/XS, approved, lgtm

#1008 🐛 Pass ns to apply_bm_hosts func in tilt to avoid creating BMHs in default ns
  scripts/deploy_tilt_env.sh
Labels: size/XS, approved, lgtm

#1000 Introduce Ubuntu 22.04 uplift related changes
  01_prepare_host.sh
  README.md
  lib/common.sh
  lib/images.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#1015 Fix minikube error creating bridge interface virbr0: File exists
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#997 ✨Add kubesec to metal3-dev-env
  .github/workflows/kubesec.yml
  template/sarif.tpl
Labels: size/L, approved, lgtm
