Repository metal3-io/metal3-dev-env, pull requests merged in 2022-02, with the labels that each got.

#927 Temporary fix for cert-manager URL change
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-upgrade-test.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-vars.yaml
Labels: size/S, approved, lgtm

#929 Use latest CAPI release v1.1.0
  lib/releases.sh
Labels: size/XS, approved, lgtm

#930 Revert "Temporary fix for cert-manager URL change"
  03_launch_mgmt_cluster.sh
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-upgrade-test.yaml
  vm-setup/roles/v1aX_integration_test/templates/clusterctl-vars.yaml
Labels: size/S, approved, lgtm

#932 Update image location as airship renamed metal3
  config_example.sh
  lib/images.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#935 Update CI badges with Metal3
  README.md
  scripts/feature_tests/README.md
Labels: size/M, approved, lgtm

#939 Uplift kustomize v4.4.1
  lib/common.sh
Labels: size/XS, approved, lgtm

#912 Use the virt-rhel8.2.0 machine type in case of arm64
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: size/XS, approved, lgtm, ok-to-test

#941 Always chown the working dir to the current user
  lib/common.sh
Labels: size/XS, approved, lgtm

#940 :seedling: Remove jan as an active reviewer
  OWNERS
  renovate.json
Labels: size/XS, approved, lgtm

#942 Fix chmod to run with sudo
  lib/common.sh
Labels: size/XS, approved, lgtm

#944 Ensure working dir files are owned by the current user
  lib/common.sh
Labels: size/XS, approved, lgtm

#945 Make IMAGE_OS value lower case
  README.md
  config_example.sh
  lib/images.sh
  scripts/feature_tests/README.md
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/M, approved, lgtm

#948 Make IMAGE_OS case sensitive again
  lib/images.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml
  vm-setup/roles/v1aX_integration_test/tasks/main.yml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers.yaml
Labels: size/M, approved, lgtm

#947 Uplift CAPM3 reference to v1.1.0
  lib/releases.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#903 Add the new epel-next repository for CentOS Stream
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#952 🌱 Fetch CAPM3RELEASE from the Github
  lib/releases.sh
Labels: size/XS, approved, lgtm

#953 🐛 Downgrade k8s version to v1.23.2 to fix CentOS integration tests
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#938 📖 Remove v1a4 main job CI badges from Readme
  README.md
Labels: size/XS, approved, lgtm

#954 🐛 Fix network interface commands for centos hosts
  lib/common.sh
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers-kubeadm-config-centos.yaml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm
