Repository metal3-io/metal3-dev-env, pull requests merged in 2022-01, with the labels that each got.

#900 Change ironic image tag to main
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/XS, approved, lgtm

#894 Make upgrade test CAPI v1a4 -> v1b1
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/L, approved, lgtm

#904 Allow overriding CAPM3_VERSION and CAPI_VERSION in upgrade vars
  scripts/feature_tests/upgrade/upgrade_vars.sh
Labels: size/XS, approved, lgtm

#902 Handle zero length dhcp_range variables
  vm-setup/roles/libvirt/templates/network.xml.j2
Labels: size/XS, approved, lgtm

#891 CI: prepare for the new ironic container
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
Labels: size/M, approved, lgtm

#905 Ensure that machines are provisioned and running before repivot
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/remediation.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify.yml
  vm-setup/roles/v1aX_integration_test/tasks/verify_resources_states.yml
Labels: size/L, approved, lgtm

#906 move maelk to emeritus_approvers list
  OWNERS
Labels: size/XS, approved, lgtm

#907 Add Lennart Jern as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#910 🌱 Add logic to verify passwordless sudo
  lib/common.sh
Labels: size/XS, approved, lgtm

#919 Uplift minikube to 1.25.1 and comment out few renovate updates
  lib/common.sh
  renovate.json
Labels: size/S, approved, lgtm

#914 uplift KUBERNETES_VERSION to v1.23.3
  config_example.sh
  lib/common.sh
  scripts/feature_tests/feature_test_vars.sh
  scripts/feature_tests/node_reuse/node_reuse_vars.sh
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vars.md
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#920 Remove extra '/' from IMAGE_LOCATION
  lib/images.sh
  vm-setup/roles/v1aX_integration_test/tasks/node_reuse.yml
  vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#922 🌱Increase retry of verifying number of ready m3machine resources
  vm-setup/roles/v1aX_integration_test/tasks/verify_resources_states.yml
Labels: size/XS, approved, lgtm
