Repository metal3-io/metal3-dev-env, pull requests merged in 2022-11, with the labels that each got.

#1096 Install passlib from rpm
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: size/M, approved, lgtm

#1098 IPA downloader exit on error
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#1099 add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: size/S, approved, lgtm

#1105 🌱 Pin CAPM3 to v1.3.0-beta.0 pre-release for main jobs
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1106 Use CAPI/CAPM3 pre-releases in main tests
  lib/releases.sh
Labels: size/S, approved, lgtm

#1110 Change some env var names to same ones in CAPI
  config_example.sh
  lib/common.sh
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/healthcheck/Makefile
  tests/feature_tests/node_reuse/Makefile
  tests/feature_tests/pivoting/Makefile
  tests/feature_tests/pivoting/upgrade.sh
  tests/feature_tests/remediation/Makefile
  tests/feature_tests/upgrade/upgrade_vars.sh
  tests/roles/run_tests/tasks/cleanup.yml
  tests/roles/run_tests/tasks/generate_templates.yml
  tests/roles/run_tests/tasks/move.yml
  tests/roles/run_tests/tasks/node_reuse.yml
  tests/roles/run_tests/tasks/remediation.yml
  tests/roles/run_tests/tasks/verify_resources_states.yml
  tests/roles/run_tests/templates/cluster-template-controlplane.yaml
  tests/roles/run_tests/templates/cluster-template-workers.yaml
  tests/roles/run_tests/templates/clusterctl-vars.yaml
  tests/roles/run_tests/vars/main.yml
  tests/test.sh
  vars.md
Labels: size/M, approved, lgtm

#1100 Support multiple instances in the same network
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/network.sh
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1109 Use SQlite for Ironic
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#1108 Upgrade from k8s v1.23.8 to v1.25.x in two steps
  tests/feature_tests/upgrade/upgrade_vars.sh
  tests/roles/run_tests/tasks/upgrade.yml
  tests/roles/run_tests/tasks/upgrade_k8s.yml
Labels: size/L, approved, lgtm

#1086 Ironic kustomize components
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm, do-not-merge/hold

#1114 Fix ironic_bmo_configmap path with v0.1.2
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#1115 Use ansible 7.0.0 only for Ubuntu 22.x
  lib/common.sh
Labels: size/XS, approved, lgtm

#1116 Fix BMOBRANCH var while kustomization
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm
