Repository metal3-io/metal3-dev-env, pull requests merged in 2022-07, with the labels that each got.

#1033 Make wget less verbose
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#1036 🐛 Fix test scripts paths used in v1alpha5 e2e
  tests/scripts/generate-template.sh
  tests/scripts/run_command.sh
Labels: size/XS, approved, lgtm

#1035 Fix readme test paths
  README.md
Labels: size/XS, approved, lgtm

#1038 Update build badge links
  README.md
Labels: size/XS, approved, lgtm

#1039 Use CAPM3RELEASEBRANCH from jjb instead of setting it based on API Version
  lib/common.sh
Labels: size/S, approved, lgtm

#1040 Uplift centos img version of node_reuse test
  tests/feature_tests/node_reuse/node_reuse_vars.sh
Labels: size/XS, approved, lgtm

#1041 🐛 Fix unbound CAPM3RELEASEBRANCH for local tests
  lib/common.sh
Labels: size/XS, approved, lgtm

#1043 📖 Add Sunnatillo and Adam Rozman to reviewers list
  OWNERS
Labels: size/XS, approved, lgtm

#1044 Fix METAL3_DIR path for provisioning and deprovisioning files
  tests/scripts/deprovision/cluster.sh
  tests/scripts/deprovision/controlplane.sh
  tests/scripts/deprovision/worker.sh
  tests/scripts/provision/cluster.sh
  tests/scripts/provision/controlplane.sh
  tests/scripts/provision/pivot.sh
  tests/scripts/provision/worker.sh
Labels: size/S, approved, lgtm

#998 🌱 Uplift k8s version to 1.24.1
  config_example.sh
  lib/common.sh
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
  tests/feature_tests/upgrade/upgrade_vars.sh
  tests/roles/run_tests/tasks/healthcheck.yml
  tests/roles/run_tests/tasks/node_reuse.yml
  tests/roles/run_tests/tasks/upgrade.yml
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1047 Use different K8s version for capm3 0.5 tests
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
Labels: size/S, approved, lgtm

#1049 Move hardys to emeritus_approvers
  OWNERS
Labels: size/XS, approved, lgtm
