Repository metal3-io/metal3-dev-env, pull requests merged in 2022-04, with the labels that each got.

#977 Add missing directory in Ubuntu
  01_prepare_host.sh
  renovate.json
Labels: size/XS, approved, lgtm

#978 Fix unversioned python on CentOS
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#980 Ensure python3 is installed before linking to it
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#979 Revert "Set BMO and Ironic tags based on CAPM3 release"
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  renovate.json
  scripts/feature_tests/cleanup_env.sh
  scripts/run.sh
  scripts/run_command.sh
Labels: size/M, approved, lgtm

#976 Uplift CAPM3RELEASE to v1.1.1 & CAPIRELEASE to v1.1.3
  scripts/feature_tests/upgrade/upgrade_vars.sh
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#984 FIx permission denied error in BML
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#983 Check ironic deployment instead of pods after pivot
  vm-setup/roles/v1aX_integration_test/filter_plugins/status.py
  vm-setup/roles/v1aX_integration_test/tasks/move.yml
Labels: size/M, approved, lgtm

#988 Replace curl with wget
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#991 Delete host as part of cluster clean up
  03_launch_mgmt_cluster.sh
  scripts/run.sh
  vm-setup/roles/v1aX_integration_test/tasks/cleanup.yml
  vm-setup/roles/v1aX_integration_test/vars/main.yml
Labels: size/S, approved, lgtm

#995 Avoid overiding working dir in playbooks
  scripts/run.sh
Labels: size/XS, approved, lgtm

#996 Uplift CentOS node images to use stream 9 and install additional CentOS packages
  README.md
  lib/images.sh
  vars.md
  vm-setup/roles/packages_installation/defaults/main.yml
Labels: size/S, approved, lgtm
