Repository metal3-io/metal3-dev-env, pull requests merged in 2022-08, with the labels that each got.

#1053 Only add krew path to .bashrc if not there
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1054 Inject ssh key also in ironic ramdisk
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: size/XS, approved, lgtm

#1050 🌱 Bump CAPI and CAPM3 to v1.2.x
  lib/releases.sh
  tests/feature_tests/upgrade/upgrade_vars.sh
  tests/roles/run_tests/tasks/upgrade.yml
Labels: size/M, approved, lgtm

#1056 Fix IPAM image usage for CAPM3 release-1.1 branch
  lib/common.sh
Labels: size/S, approved, lgtm

#1055 For live-iso setting one node to always use redfish-virtualmedia
  02_configure_host.sh
  host_cleanup.sh
  lib/common.sh
  tests/roles/run_tests/tasks/cleanup.yml
  tests/roles/run_tests/tasks/inspection.yml
  tests/roles/run_tests/vars/main.yml
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: size/M, approved, lgtm

#1057 Move fmuyassarov to emeritus_approvers
  OWNERS
Labels: size/XS, approved, lgtm

#1048 Reconfigure network settings from network-scripts to keyfile format
  02_configure_host.sh
  host_cleanup.sh
Labels: size/L, approved, lgtm

#1009 Change Centos target nodes network configuration to keyfile format
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
Labels: size/M, approved, lgtm

#1059 Removed redfish virtual media flavor
  02_configure_host.sh
  host_cleanup.sh
  lib/common.sh
  tests/roles/run_tests/tasks/cleanup.yml
  tests/roles/run_tests/tasks/inspection.yml
  tests/roles/run_tests/vars/main.yml
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/libvirt/templates/ironic_nodes.json.j2
Labels: size/M, approved, lgtm

#1062 Add autoconnect priority to centos target node network config
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
Labels: size/XS, approved, lgtm

#1064 Fix cert-manager version to v1.9.1 and also fix clusterctl.yaml templating
  03_launch_mgmt_cluster.sh
  tests/roles/run_tests/tasks/generate_templates.yml
Labels: size/S, approved, lgtm
