Repository metal3-io/metal3-dev-env, pull requests merged in 2023-08, with the labels that each got.

#1267 Download and install kvm2 driver with minikube
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1270 Add kubectl describe output logs for target cluster
  tests/scripts/fetch_target_logs.sh
Labels: size/XS, approved, lgtm

#1271 add python3-dev for libvirt-python building
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1275 Rename target node memory variable
  02_configure_host.sh
  lib/common.sh
  tests/roles/run_tests/vars/main.yml
  vars.md
  vm-setup/roles/common/defaults/main.yml
Labels: size/S, approved, lgtm

#1268 Bump CAPI to v1.5.0
  03_launch_mgmt_cluster.sh
  lib/releases.sh
  tests/roles/run_tests/tasks/generate_templates.yml
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1272 fix local ironic image building and ipa downloader logic
  02_configure_host.sh
  lib/common.sh
  vars.md
Labels: size/L, approved, lgtm

#1276 Adding default value for LOCAL_IPA_PATH
  lib/common.sh
Labels: size/XS, approved, lgtm

#1278 Bump k8s version to v1.28.1
  config_example.sh
  lib/common.sh
  renovate.json
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/S, approved, lgtm

#1279 Add release-1.5 branch config for CAPM3 and IPAM
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/M, approved, lgtm

#1280 fix KUBECTL_SHA256 to match KUBERNETES_VERSION
  lib/common.sh
Labels: size/XS, approved, lgtm

#1284 Bump golang to v1.20.7
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm

#1282 Add version check to kubectl installation
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1287 Point CAPM3RELEASE to v1.5.99 for release-1.5 branch
  lib/releases.sh
Labels: size/XS, approved, lgtm
