Repository metal3-io/metal3-dev-env, pull requests merged in 2023-05, with the labels that each got.

#1215 Remove release-0.5 mentions in dev-env
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1224 Bump k8s to v1.27.1
  config_example.sh
  lib/common.sh
  renovate.json
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/S, approved, lgtm

#1229 Fix CAPM3RELEASE to v1.4.99 for main branch
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1225 Bump calico to v3.25.1
  tests/roles/run_tests/tasks/verify.yml
  tests/roles/run_tests/vars/main.yml
Labels: size/XS, approved, lgtm

#1230 Changing defaults from md5 to sha256
  01_prepare_host.sh
  lib/images.sh
  tests/roles/run_tests/tasks/download_image.yml
  tests/roles/run_tests/vars/main.yml
Labels: size/M, approved, lgtm

#1174 Add optional fully NATed network configuration
  03_launch_mgmt_cluster.sh
  lib/network.sh
  tests/roles/run_tests/tasks/verify.yml
  tests/roles/run_tests/tasks/verify_resources_states.yml
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
  ubuntu_bridge_network_configuration.sh
  vars.md
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/common/tasks/main.yml
Labels: size/L, approved, lgtm

#1226 Exclude install requirement script from CI tests
  01_prepare_host.sh
  02_configure_host.sh
  Makefile
  lib/image_prepull.sh
  tests/feature_tests/setup_env.sh
Labels: size/L, approved, lgtm

#1232 Move clusterctl installation to support older version of releases
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
Labels: size/S, approved, lgtm

#1235 Drop CAPM3 release-1.1 test support
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1238 fix incorrect subnet lookup of the iptable config
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/iptables.yaml
Labels: size/XS, approved, lgtm

#1237 add improvements to the test kubeadm scripts
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-ubuntu.yaml
Labels: size/M, approved, lgtm
