Repository metal3-io/metal3-dev-env, pull requests merged in 2023-12, with the labels that each got.

#1320 bump markdownlint to 0.13.0
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#1321 Bump CAPI to v1.6 and export CAPM3 diagnostics var for clusterctl
  lib/releases.sh
  tests/roles/run_tests/templates/clusterctl-vars.yaml
  tests/roles/run_tests/vars/main.yml
Labels: size/S, approved, lgtm

#1328 use locally built images in pivoting tests too
  02_configure_host.sh
  lib/common.sh
  tests/run.sh
Labels: approved, lgtm, size/XL

#1330 fix ironic building from source in PR test
  02_configure_host.sh
Labels: size/XS, approved, lgtm
