Repository metal3-io/metal3-dev-env, pull requests merged in 2023-07, with the labels that each got.

#1257 Revert "Use MariaDB instead of SQLite"
  03_launch_mgmt_cluster.sh
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/XS, approved, lgtm

#1258 Add @mboukhalfa and @smoshiur1237 as approvers
  OWNERS
Labels: size/XS, approved, lgtm

#1254 Add a check before deleting virbr0 to avoid errors in the loop
  02_configure_host.sh
Labels: size/XS, approved, lgtm, ok-to-test

#1253 Allow proxy connection when dividing response
  lib/releases.sh
Labels: size/XS, approved, lgtm, ok-to-test

#1261 Fix incorrect EFI firmware reference in VM template
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: size/XS, approved, lgtm

#1262 Bump minikube to v1.31.1
  lib/common.sh
Labels: size/XS, approved, lgtm

#1263 Bump k8s version to v1.27.4
  config_example.sh
  lib/common.sh
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/S, approved, lgtm

#1265 Fix minikube delete hanging issue
  cluster_cleanup.sh
Labels: size/XS, approved, lgtm
