Repository metal3-io/metal3-dev-env, pull requests merged in 2023-01, with the labels that each got.

#1132 Remove downgrading NetworkManager
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#1127 Support deploying Ironic with/without MariaDB
  03_launch_mgmt_cluster.sh
  tests/roles/run_tests/tasks/move.yml
  tests/roles/run_tests/tasks/move_back.yml
  tests/roles/run_tests/tasks/upgrade.yml
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1133 .github: secure github actions
  .github/workflows/kubesec.yml
Labels: size/S, approved, lgtm

#1134 Change deprecated egrep with grep -E
  tests/roles/run_tests/tasks/node_reuse.yml
  tests/roles/run_tests/tasks/remediation.yml
Labels: size/XS, approved, lgtm

#1135 uplift golang to 1.19.4
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm

#1136 use docker.io consistently as image registry
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#1140 Adding deprovisioning of kcp and worker back.
  tests/roles/run_tests/tasks/main.yml
  tests/roles/run_tests/vars/main.yml
Labels: size/S, approved, lgtm

#1141 install kubectl completion file by default
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1145 Remove yarn repo
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: size/S, approved, lgtm

#1146 update readme
  README.md
Labels: size/M, approved, lgtm
