Repository metal3-io/metal3-dev-env, pull requests merged in 2023-04, with the labels that each got.

#1198 Add support for building mariadb image
  02_configure_host.sh
  lib/common.sh
  vars.md
Labels: size/S, approved, lgtm

#1196 Explicitly set IRONIC_FROM_SOURCE default to false
  lib/common.sh
Labels: size/XS, approved, lgtm

#1193 Improve shell syntax (1)
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  hack/run-bmo-loop.sh
  lib/common.sh
  tests/test.sh
Labels: size/L, approved, lgtm

#1199 Allow custom source to build ironic-image from source
  02_configure_host.sh
  vars.md
Labels: size/S, approved, lgtm

#1203 Fix IPA_BASEURI default value
  01_prepare_host.sh
Labels: size/XS, approved, lgtm, ok-to-test

#1205 Refactor target log collection script
  tests/scripts/fetch_target_logs.sh
Labels: size/S, approved, lgtm

#1206 Fix manifest image update and image tag for Keepalived
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: size/XS, approved, lgtm

#1208 Fix BMOBRANCH based on CAPM3 release branch.
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1207 Fix manifest collection for integration test
  tests/roles/run_tests/vars/main.yml
  tests/scripts/fetch_manifests.sh
  tests/test.sh
Labels: size/S, approved, lgtm

#1212 Remove leftover ISO images from the default pool
  vm-setup/roles/libvirt/tasks/vm_teardown_tasks.yml
Labels: size/XS, approved, lgtm

#1216 Add manifest collection after re-pivot
  Makefile
  tests/scripts/fetch_manifests.sh
  tests/test.sh
Labels: size/S, approved, lgtm

#1217 Add manifest collection after pivot and rearrange the manifest directories
  Makefile
  tests/scripts/fetch_manifests.sh
  tests/test.sh
Labels: size/S, approved, lgtm

#1222 Add release-1.4 branch config for CAPM3 and IPAM
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm
