Repository metal3-io/metal3-dev-env, pull requests merged in 2023-06, with the labels that each got.

#1244 Fix running consecutive make test
  tests/roles/run_tests/tasks/main.yml
Labels: size/S, approved, lgtm

#1245 add mitigation for kubeadm join issue
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-ubuntu.yaml
Labels: size/M, approved, lgtm

#1236 pin downloaded scripts and binaries to a sha digest
  01_prepare_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/download.sh
  vars.md
Labels: size/L, approved, lgtm

#1247 Fix package installation for ubuntu 20
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: size/XS, approved, lgtm

#1251 move sourcing of libs after initial package install
  01_prepare_host.sh
Labels: size/S, approved, lgtm

#1143 Remove and reinstall BMO in source cluster before and after pivot
  tests/roles/run_tests/tasks/move.yml
  tests/roles/run_tests/tasks/move_back.yml
Labels: size/S, approved, lgtm

#1252 Removed ansible-based feature tests.
  Makefile
  tests/feature_tests/README.md
  tests/feature_tests/cleanup_env.sh
  tests/feature_tests/feature_test_deprovisioning.sh
  tests/feature_tests/feature_test_provisioning.sh
  tests/feature_tests/feature_test_vars.sh
  tests/feature_tests/healthcheck/Makefile
  tests/feature_tests/healthcheck/healthcheck.sh
  tests/feature_tests/inspection_test.sh
  tests/feature_tests/node_reuse/Makefile
  tests/feature_tests/node_reuse/node_reuse.sh
  tests/feature_tests/node_reuse/node_reuse_vars.sh
  tests/feature_tests/pivoting/Makefile
  tests/feature_tests/pivoting/pivot.sh
  tests/feature_tests/pivoting/repivot.sh
  tests/feature_tests/pivoting/upgrade.sh
  tests/feature_tests/remediation/Makefile
  tests/feature_tests/remediation/remediation.sh
  tests/feature_tests/setup_env.sh
  tests/roles/run_tests/tasks/healthcheck.yml
  tests/roles/run_tests/tasks/inspection.yml
  tests/roles/run_tests/tasks/main.yml
  tests/roles/run_tests/tasks/node_reuse.yml
  tests/roles/run_tests/tasks/remediation.yml
  tests/roles/run_tests/vars/main.yml
Labels: approved, lgtm, size/XXL
