Repository metal3-io/metal3-dev-env, pull requests merged in 2023-09, with the labels that each got.

#1283 add a helper script to print digests of downloaded artifacts
  hack/print_checksums.sh
  lib/download.sh
Labels: size/M, approved, lgtm

#1289 make sha256 digests overridable for upgrade tests
  lib/common.sh
Labels: size/S, approved, lgtm

#1292 Bump minikube to v1.31.2
  cluster_cleanup.sh
  lib/common.sh
Labels: size/S, approved, lgtm

#1294 Fix README link to Getting started with Metal3
  README.md
Labels: size/XS, approved, lgtm, ok-to-test

#1296 Fix CAPI config folder location
  host_cleanup.sh
  lib/releases.sh
  tests/roles/run_tests/templates/clusterctl-vars.yaml
  tilt-setup/deploy_tilt_env.sh
Labels: size/S, approved, lgtm
