Repository metal3-io/metal3-dev-env, pull requests merged in 2023-03, with the labels that each got.

#1161 🐛 Workaround to fix github api limit for capi release
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1159 Remove deprecated apt_key ansible module
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: size/M, approved, lgtm

#1168 Use pagination when requesting github API
  lib/releases.sh
Labels: size/M, approved, lgtm

#1171 remove obsolete OWNERS in feature_tests
  tests/feature_tests/OWNERS
Labels: size/XS, approved, lgtm

#1160 Allow metal3-dev-env to run on a generic ubuntu VM
  01_prepare_host.sh
  02_configure_host.sh
  README.md
  lib/common.sh
  vars.md
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/firewall/tasks/iptables.yaml
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/ubuntu_required_packages.yml
Labels: size/L, approved, lgtm

#1173 Fetch target cluster logs before re-pivot
  Makefile
  tests/feature_tests/pivoting/Makefile
  tests/roles/run_tests/vars/main.yml
  tests/scripts/fetch_target_logs.sh
  tests/test.sh
Labels: size/M, approved, lgtm

#1176 Unify ansible extra_var handling
  02_configure_host.sh
  host_cleanup.sh
  lib/common.sh
  vm-setup/roles/firewall/tasks/main.yml
Labels: size/S, approved, lgtm

#1182 Fix redefinition of OS variable during krew install
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1179 Add firewalld cleanup
  host_cleanup.sh
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/firewall/tasks/main.yml
Labels: size/M, approved, lgtm

#1183 Bump CAPI to v1.4.x
  03_launch_mgmt_cluster.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1186 remove k8s from renovate config
  renovate.json
Labels: size/S, approved, lgtm

#1191 Tag capm3 1.4.0 release with 1.4.99 until we have a proper release
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1169 Refactor dev-env variable names
  01_prepare_host.sh
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  04_verify.sh
  README.md
  clouds.yaml.j2
  config_example.sh
  host_cleanup.sh
  lib/common.sh
  lib/images.sh
  lib/ironic_tls_setup.sh
  lib/network.sh
  tests/roles/run_tests/templates/cluster-template-cluster.yaml
  tests/roles/run_tests/templates/clusterctl-vars.yaml
  tests/roles/run_tests/templates/metal3datatemplate-template.yaml
  tests/roles/run_tests/vars/main.yml
  ubuntu_bridge_network_configuration.sh
  vars.md
  vm-setup/library/generate_macs.py
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/firewall/defaults/main.yml
  vm-setup/roles/firewall/tasks/firewalld.yaml
  vm-setup/roles/firewall/tasks/iptables.yaml
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/tasks/network_teardown_tasks.yml
Labels: size/L, approved, lgtm

#1187 Remove mentions of v1alpha5
  04_verify.sh
  README.md
  config_example.sh
  lib/common.sh
  lib/releases.sh
  tests/roles/run_tests/templates/cluster-template-controlplane.yaml
  tests/roles/run_tests/templates/cluster-template-workers.yaml
  vars.md
Labels: size/M, approved, lgtm

#1192 Fix BMO branching and tags for different CAPM3 release branches
  03_launch_mgmt_cluster.sh
  README.md
  lib/common.sh
Labels: size/M, approved, lgtm

#1195 Fix BMO local image building workflow
  lib/common.sh
Labels: size/XS, approved, lgtm
