Repository metal3-io/metal3-dev-env, pull requests merged in 2024-09, with the labels that each got.

#1453 use new ironic-image 26.0.0 release for release-1.8
  README.md
  lib/common.sh
Labels: size/XS, approved, lgtm

#1454 bump BMO tags after releases and drop 1.5 config
  lib/common.sh
Labels: size/S, approved, lgtm

#1455 bump Ironic-image versions
  lib/common.sh
Labels: size/XS, approved, lgtm

#1456 :seedling: Fix `make` pass if ironic endpoint returns 000
  04_verify.sh
Labels: size/XS, approved, lgtm

#1451 :seedling: Remove release 1.5 branch config
  03_launch_mgmt_cluster.sh
  README.md
  lib/common.sh
  lib/releases.sh
  vars.md
  vm-setup/install-package-playbook.yml
Labels: size/S, approved, lgtm

#1460 Bump minikube to v1.34.0
  lib/common.sh
Labels: size/XS, approved, lgtm

#1458 Allowing downloadable checksums and different checksum formats
  lib/common.sh
  lib/download.sh
Labels: size/M, approved, lgtm
