Repository metal3-io/metal3-dev-env, pull requests merged in 2024-04, with the labels that each got.

#1378 Bump ironic-image to v24.1.0
  README.md
  lib/common.sh
Labels: size/XS, approved, lgtm

#1382 Downgrade ironic-image to v24.0.0 for release-1.6 branch
  README.md
  lib/common.sh
Labels: size/XS, approved, lgtm

#1379 Bump golang to v1.21.9 and kind to 0.22.0
  lib/common.sh
  vm-setup/install-package-playbook.yml
Labels: size/S, approved, lgtm

#1381 Add release-1.7 branch config for CAPM3 and IPAM
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/M, approved, lgtm

#1389 bump k8s to v1.30.0
  config_example.sh
  lib/common.sh
  renovate.json
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1392 Bump minikube to v1.33.0
  lib/common.sh
Labels: size/XS, approved, lgtm
