Repository metal3-io/metal3-dev-env, pull requests merged in 2024-06, with the labels that each got.

#1411 Bump golang to v1.22.3
  renovate.json
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm

#1414 :seedling: Update bmo and keepalived tags for release-1.7
  README.md
  lib/common.sh
Labels: size/XS, approved, lgtm

#1415 tie BMO commits for CAPM3RELEASEBRANCH variables
  lib/common.sh
Labels: size/XS, approved, lgtm

#1419 Install ansible in a virtual environment
  01_prepare_host.sh
  02_configure_host.sh
  host_cleanup.sh
  lib/common.sh
  tests/run.sh
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/S, approved, lgtm

#1421 Enable the use of local node images
  lib/image_prepull.sh
Labels: size/S, approved, lgtm

#1422 Remove CentOS Stream 8 configuration leftovers
  lib/common.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/centos_required_packages.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/M, approved, lgtm

#1426 Always re-install Ansible in the venv
  01_prepare_host.sh
Labels: size/XS, approved, lgtm

#1427 Use Python from the Ansible venv when importing Jinja2
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#1428 restore centos required packages task
  vm-setup/roles/packages_installation/tasks/centos_required_packages.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/M, approved, lgtm

#1429 Remove support for Ubuntu 18 Bionic
  01_prepare_host.sh
  lib/common.sh
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/S, approved, lgtm

#1432 Add namespace directory in manifest collection
  tests/scripts/fetch_manifests.sh
Labels: size/XS, approved, lgtm

#1431 Update build status links for dev env tests
  README.md
Labels: size/S, approved, lgtm
