Repository metal3-io/metal3-dev-env, pull requests merged in 2024-11, with the labels that each got.

#1468 🌱 Uplift k8s to v1.31.2
  config_example.sh
  lib/common.sh
  tests/roles/run_tests/vars/main.yml
Labels: size/S, approved, lgtm

#1469 :seedling: Add cleaning up fake-ipa container to make clean
  host_cleanup.sh
Labels: size/XS, approved, lgtm

#1465 Add PoCs folder and descriptions
  PoCs/README.md
Labels: size/L, approved, lgtm

#1471 use uuidgen to generate random username/password
  lib/ironic_basic_auth.sh
Labels: size/XS, approved, lgtm

#1466 Initial support for ironic-standalone-operator
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/common.sh
  lib/ironic_basic_auth.sh
  lib/network.sh
  vars.md
Labels: size/L, approved, lgtm

#1475 cleanup and reformat bash files at repositor root
  cluster_cleanup.sh
  disable_apparmor_driver_libvirtd.sh
  host_cleanup.sh
  openstackclient.sh
  ubuntu_bridge_network_configuration.sh
  vbmc.sh
Labels: size/L, approved, lgtm

#1476 cleanup and reformat 01 script bash syntax
  01_prepare_host.sh
Labels: size/L, approved, lgtm

#1478 Temporary pin ironic-standalone-operator image
  02_configure_host.sh
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: size/XS, approved, lgtm
