Repository metal3-io/metal3-dev-env, pull requests merged in 2024-05, with the labels that each got.

#1390 :seedling: Update Kustomize version
  lib/common.sh
Labels: size/XS, approved, lgtm

#1395 Fix kustomize v5.4.1 sha value
  lib/common.sh
Labels: size/XS, approved, lgtm

#1396 There is conflicting rpm packages add --nobest flag
  01_prepare_host.sh
  vm-setup/roles/packages_installation/tasks/centos_required_packages.yml
Labels: size/XS, approved, lgtm

#1399 🌱 Move furkatgofurov7 to emeritus approvers
  OWNERS
  renovate.json
Labels: size/XS, approved, lgtm

#1400 speed up git cloning in dev-env
  lib/common.sh
Labels: size/S, approved, lgtm

#1403 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: size/M, approved, lgtm

#1407 remove kubesec workflow
  .github/workflows/kubesec.yml
Labels: size/M, approved, lgtm

#1410 shellcheck only files
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm
