Repository metal3-io/metal3-dev-env, pull requests merged in 2024-01, with the labels that each got.

#1333 Add release-1.6 branch config for CAPM3 and IPAM
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1336 remove release 1.3 support
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/M, approved, lgtm

#1273 introducing custom iPXE firmware buiding support
  03_launch_mgmt_cluster.sh
  lib/common.sh
  lib/ironic_tls_setup.sh
Labels: size/M, approved, lgtm

#1334 Bump k8s & kind node image version to v1.29.0
  config_example.sh
  lib/common.sh
  renovate.json
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/S, approved, lgtm

#1337 Bump minikube to v1.32.0
  lib/common.sh
Labels: size/XS, approved, lgtm

#1339 Update kustomize phony for CAPM3
  03_launch_mgmt_cluster.sh
Labels: size/XS, approved, lgtm

#1338 switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  hack/markdownlint.sh
  vars.md
Labels: size/M, approved, lgtm

#1343 Bump golang to v1.21.6
  renovate.json
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm
