Repository metal3-io/metal3-dev-env, pull requests merged in 2024-08, with the labels that each got.

#1445 remove duplicates from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#1444 🌱 bump k8s to v1.31.0
  config_example.sh
  lib/common.sh
  lib/releases.sh
  renovate.json
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/M, approved, lgtm

#1449 Silence fetch logs and fetch manifests
  tests/scripts/fetch_manifests.sh
  tests/scripts/fetch_target_logs.sh
Labels: size/XS, approved, lgtm

#1443 :seedling: Add release-1.8-branch-config
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/S, approved, lgtm

#1452 🌱 Fixing CAPM3RELEASE for main branch
  lib/releases.sh
Labels: size/XS, approved, lgtm
