Repository metal3-io/metal3-dev-env, pull requests merged in 2025-04, with the labels that each got.

#1517 Pin collections to latest ansible 2.15 compatible versions
  vm-setup/requirements.yml
Labels: size/XS, approved, lgtm, ok-to-test

#1520 Use Ansible 8 in CentOS Stream 9
  lib/common.sh
Labels: size/XS, approved, lgtm

#1521 Remove ancient ansible version
  lib/common.sh
Labels: size/XS, approved, lgtm

#1513 add option to toggle dev-env host package updates
  01_prepare_host.sh
  02_configure_host.sh
  Makefile
  vars.md
Labels: size/M, approved, lgtm

#1524 Bump Kubernetes to 1.33.0
  config_example.sh
  lib/common.sh
  renovate.json
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/S, approved, lgtm

#1525 🌱 Fixing get_latest_release_from_goproxy
  lib/releases.sh
Labels: size/XS, approved, lgtm
