Repository metal3-io/metal3-dev-env, pull requests merged in 2025-09, with the labels that each got.

#1566 🌱 Remove hard coded version of CAPIRELEASE
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1568 Add support for release-1.11
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/M, approved, lgtm

#1570 Fix filetype check
  lib/common.sh
Labels: size/XS, approved, lgtm

#1561 Change interface name after enabling predicted interface names
  03_launch_mgmt_cluster.sh
  config_example.sh
  lib/common.sh
  tests/roles/run_tests/templates/main/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/main/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/main/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/main/cluster-template-workers-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.10/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.10/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.10/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.10/cluster-template-workers-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.8/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.8/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.8/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.8/cluster-template-workers-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.9/cluster-template-controlplane-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.9/cluster-template-controlplane-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/templates/release-1.9/cluster-template-workers-kubeadm-config-centos.yaml
  tests/roles/run_tests/templates/release-1.9/cluster-template-workers-kubeadm-config-ubuntu.yaml
  tests/roles/run_tests/vars/main.yml
  vars.md
Labels: size/L, approved, lgtm

#1571 Bump minikube to v1.37.0
  lib/common.sh
Labels: size/XS, approved, lgtm
