Repository metal3-io/metal3-dev-env, pull requests merged in 2025-05, with the labels that each got.

#1526 :seedling: All images point to release branches
  lib/common.sh
Labels: size/S, approved, lgtm

#1523 :seedling: Add Support for release-1.10
  README.md
  lib/common.sh
  lib/releases.sh
Labels: size/M, approved, lgtm

#1522 :sparkles: Support CentOS Stream 10
  01_prepare_host.sh
  lib/common.sh
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
  vm-setup/roles/packages_installation/defaults/main.yml
  vm-setup/roles/packages_installation/tasks/main.yml
Labels: size/S, approved, lgtm

#1529 🌱 Fix source branches of other repos for CAPM3RELEASEBRANCH release-1.10
  lib/common.sh
Labels: size/XS, approved, lgtm

#1532 Improve applying BMHs
  03_launch_mgmt_cluster.sh
  03_launch_mgmt_cluster_pre_1_10.sh
Labels: size/M, approved, lgtm, ok-to-test

#1531 Add check for ironic deployments to fix the centOS test failure when SKIP_APPLY_BMH enabled
  04_verify.sh
Labels: size/S, approved, lgtm

#1528 Add redfish SSL support
  03_launch_mgmt_cluster.sh
  03_launch_mgmt_cluster_pre_1_10.sh
  04_verify.sh
  lib/common.sh
  vm-setup/roles/common/templates/ironic_nodes.json.j2
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: size/M, approved, lgtm, ok-to-test

#1538 Bump golang to v1.24.3
  renovate.json
  vm-setup/install-package-playbook.yml
Labels: size/XS, approved, lgtm
