Repository metal3-io/metal3-dev-env, pull requests merged in 2025-01, with the labels that each got.

#1487 🌱 Check the default value of CAPM3RELEASE before setting it
  lib/releases.sh
Labels: size/XS, approved, lgtm

#1488 Update to the latest ironic-standalone-operator
  03_launch_mgmt_cluster.sh
  lib/common.sh
Labels: size/M, approved, lgtm

#1457 Enable 'redfish-uefihttp' as a vm_driver_tmp
  config_example.sh
  vars.md
  vm-setup/roles/common/templates/ironic_nodes.json.j2
Labels: size/XS, approved, lgtm

#1490 Add move labels to BMH CRDs
  tests/roles/run_tests/tasks/move.yml
Labels: size/XS, approved, lgtm

#1489 :book: update tested versions for release-1.7 in test matrix
  README.md
Labels: size/XS, approved, lgtm

#1326 use UEFI instead of legacy as default boot mode
  config_example.sh
  lib/common.sh
  lib/network.sh
  vars.md
  vm-setup/roles/common/tasks/vm_nodes_tasks.yml
  vm-setup/roles/libvirt/defaults/main.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: size/S, approved, lgtm, ok-to-test

#1492 Migrate ansible filters from netcommon to utils
  vm-setup/roles/common/defaults/main.yml
  vm-setup/roles/common/tasks/extra_networks_tasks.yml
  vm-setup/roles/common/templates/ironic_nodes.json.j2
  vm-setup/roles/libvirt/templates/network.xml.j2
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: size/M, approved, lgtm

#1495 Add @adilGhaffarDev and @mquhuy as reviewers
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#1494 Update renovate.json config
  renovate.json
Labels: size/S, approved, lgtm

#1493 Bump minikube to v1.35.0 and kind to v0.26.0
  lib/common.sh
Labels: size/XS, approved, lgtm

#1497 Support UEFI boot on ubuntu noble
  vm-setup/roles/common/tasks/vm_nodes_tasks.yml
  vm-setup/roles/libvirt/templates/baremetalvm.xml.j2
Labels: size/XS, approved, lgtm

#1464 🌱 Add tls certs to fakeIPA config
  03_launch_mgmt_cluster.sh
  vm-setup/roles/virtbmc/tasks/setup_tasks.yml
Labels: size/M, approved, lgtm
